### ISSUE TITLE
Multi-Raster Source is Hard-Coded Not to Use Transformers (In Some Places)

### ISSUE THREAD

**Issue by jamesmcclain** [azavea/raster-vision#1003]
While trying to use the multi-raster source with input rasters of different type (float32 and float64), I had to write a raster transformer  to make all of the sub-raster sources the same type (which is completely expected).  The unexpected part is that `use_transformers` is hard-coded to `False` in at least one place, which causes a failure in the `analyze` stage (because the transformer is not able to run and change the `dtype` of the float64 raster).

In my case the line where that occurs is [here](https://github.com/azavea/raster-vision/blob/a2f7a1b52ed1a63053c3571771699fefe6e7ed10/rastervision_core/rastervision/core/rv_pipeline/semantic_segmentation.py#L101).

**Comment by AdeelH** [comment]
I think it would break at both the analyze stage 
https://github.com/azavea/raster-vision/blob/a2f7a1b52ed1a63053c3571771699fefe6e7ed10/rastervision_core/rastervision/core/rv_pipeline/rv_pipeline.py#L50

and  `SemanticSegmentation.get_image_channels()` which uses code copied from the above
https://github.com/azavea/raster-vision/blob/a2f7a1b52ed1a63053c3571771699fefe6e7ed10/rastervision_core/rastervision/core/rv_pipeline/semantic_segmentation.py#L100-L101

The simple solution is to just change them to `True`. I don't believe that would effect MultiRasterSource in any way. Not sure about the `analyze` stage.
