### ISSUE TITLE
Allow reading directly from TIFFs during training

### ISSUE THREAD

**Issue by AdeelH** [azavea/raster-vision#1040]
The current training workflow involves first generating a training/validation dataset from large TIFFs through the `chip` command and then doing training on the resulting dataset, treating it as if it were any other image dataset.

It should be possible to skip the chipping stage entirely and read directly from the TIFFs. This is something that the `predict` stage already does. Besides saving time and disk space, this will also allow greater flexibility during training to try experimental/ad hoc things such as:
- training with multiple window sizes
- localizing loss/metrics to geographical regions

The exact implementation details will have to be worked out, but there is already some code by @jamesmcclain to do this here: https://github.com/geotrellis/deeplab-nlcd/tree/master/src/libchips

**Comment by jamesmcclain** [comment]
Another possibility place to look for inspiration is https://github.com/geotrellis/gdal-warp-bindings .  That code provides a thread-safe wrapper around GDAL.  It does not currently have Python bindings, but that should/would not be hard to produce.

**Comment by jamesmcclain** [comment]
Datasets seem to sequester each reader in a process, so there should be no thread safety concerns.
