### ISSUE TITLE
Image annotations

### ISSUE THREAD

**Issue by Tobias1234** [azavea/raster-vision#1059]
Do I have to label every object in an image tile? For instance must all buildings in a tile be annotated to get a good training result?
I am doing a land use classifiation (semantic classification),

**Comment by lewfish** [comment]
No, you can use AOIs to indicate which parts of the scene have been exhaustively labeled. See https://docs.rastervision.io/en/latest/api.html#rastervision.core.data.SceneConfig.aoi_uris
