### ISSUE TITLE
Model Predict Visualization

### ISSUE THREAD

**Issue by satyajitghana** [azavea/raster-vision#1068]
the current api for predict is `rastervision predict <model bundle> <infile> <outfile>` which when used with image detection models, and infile as an image, gives a .json file that has the detections, but how do i get the detections displayed over the image as output ? i've seen that during training this is done, i can see train sample images with annotations, can this same behavior be integrated into `predict` cli ?

**Comment by lewfish** [comment]
No, the predict command cannot do that. We use QGIS (which is scriptable) to look at predictions and imagery on a map. You could also write your own script to do this. If you go this route, you may find the the `RasterSource` and `LabelSource` classes that are in RV helpful.
