### ISSUE TITLE
Custom coordinate system

### ISSUE THREAD

**Issue by hengai** [azavea/raster-vision#1171]
How does the framework train and predict with China Geodetic Coordinate System 2000(CGCS2000)  coordinate datasets?

**Comment by AdeelH** [comment]
Currently, RV only works with vector data that is in the EPSG:4326 CRS. See https://github.com/azavea/raster-vision/blob/master/rastervision_core/rastervision/core/data/vector_source/geojson_vector_source.py.

So you will have to convert your data to EPSG:4326 before using it with RV.
