### ISSUE TITLE
Chip Command  save training images as jpg.

### ISSUE THREAD

**Issue by sagar1899** [azavea/raster-vision#1176]
i have to train TIF image with "unsigned16" datatype. but while chip command crop images are save as jpg and "byte" datatype. so there are loss of data.

how can i change croping image type and datatype ?

**Comment by AdeelH** [comment]
RV does have support for saving chips as numpy arrays, but unfortunately, that functionality is currently limited to Semantic Segmentation.

As an alternative, you can use the `StatsTransformer` (https://github.com/azavea/raster-vision/blob/master/rastervision_core/rastervision/core/data/raster_transformer/stats_transformer.py), which converts non-unit8 rasters to uint-8. You can do this via:
```python
 raster_source = RasterioSourceConfig(
     uris=[raster_uri], channel_order=[0, 1, 2], transformers=[StatsTransformerConfig()])
```
