### ISSUE TITLE
Model file .pth reuse

### ISSUE THREAD

**Issue by sagar1899** [azavea/raster-vision#1178]
I have pretrained model file like "model.pth" that contains information of car type object. but i want to train that "model.pth" with another object like tree or building so that model file contains info of car , tree and building, is that possible?
or
can i use more than one model file "model.pth" in one algorithm ?

**Comment by lewfish** [comment]
There isn't a straightforward way to do that. I would recommend creating a dataset that combines all of the classes and then train a model on that. If it's an object detection model, then you could make predictions from multiple models (assuming the classes predicted by the models are disjoint) and then take the union of the predictions.

**Comment by sagar1899** [comment]
> There isn't a straightforward way to do that. I would recommend creating a dataset that combines all of the classes and then train a model on that. If it's an object detection model, then you could make predictions from multiple models (assuming the classes predicted by the models are disjoint) and then take the union of the predictions.

how can i make predictions from multiple models ?

**Comment by lewfish** [comment]
You would just need to run the predict command separately for each model. Then you would you need to write a script which combines the prediction GeoJSON files together.
