### ISSUE TITLE
Pretrained Xview model is missing rastervision-0.13

### ISSUE THREAD

**Issue by TareqAlqutami** [azavea/raster-vision#1181]
Hello,
I can download all the pre-trained models from the model zoo at https://docs.rastervision.io/en/0.13/examples.html except the Xview model. I get the following error page:
![image](https://user-images.githubusercontent.com/46659456/124536928-7adab880-de4b-11eb-966b-389b3513423b.png)

Not sure if anyone else can download the model?

**Comment by AdeelH** [comment]
Thanks for pointing this out! It looks like there is a minor typo in the URL. It should be `model-bundle.zip` instead of `model_bundle.zip`. The correct URL is: https://s3.amazonaws.com/azavea-research-public-data/raster-vision/examples/model-zoo-0.13/xview-od/model-bundle.zip
