### ISSUE TITLE
Multiple classes in spacenet_vegas.py

### ISSUE THREAD

**Issue by hengai** [azavea/raster-vision#1207]
How can i train and predict  with multiple classes in spacenet_vegas.py.
eg：ClassConfig(names=['house', 'ancestral hall','pond','background']

**Comment by sagar1899** [comment]
in json label file you have to provide data with that labels.

means your polygons contains attribute field name "class_name" and it's value is house, pond, background.
so it will train model according to label data.

**Comment by AdeelH** [comment]
>How can i train and predict with multiple classes in spacenet_vegas.py.
>eg：ClassConfig(names=['house', 'ancestral hall','pond','background']

That is indeed how you would modify the class config. If you are encountering any errors, please share a description of your data, your `get_config()` function, and the full stack trace of the error.

**Comment by hengai** [comment]
> > How can i train and predict with multiple classes in spacenet_vegas.py.
> > eg：ClassConfig(names=['house', 'ancestral hall','pond','background']
> 
> That is indeed how you would modify the class config. If you are encountering any errors, please share a description of your data, your `get_config()` function, and the full stack trace of the error.

I trained with multiple classes for model bundle to predict, but the output of vector result has no classname.
I want to get the vector result with classname .How can i do?
