### ISSUE TITLE
Working of chip command

### ISSUE THREAD

**Issue by sagar1899** [azavea/raster-vision#1215]
i'm talking about object detection...

How chip command is works in RV ?

How image is cropped in chip size multiple images from polygons ?

can i make my own datasets and use as training dataset in RV ?

**Comment by AdeelH** [comment]
>CHIP
>Scenes are comprised of large geospatial raster sources (e.g. GeoTIFFs) and geospatial label sources (e.g. GeoJSONs), but models can only consume small images (i.e. chips) and labels in pixel based-coordinates. In addition, each Backend has its own dataset format. The CHIP command solves this problem by converting scenes into training chips and into a format the backend can use for training.

https://docs.rastervision.io/en/0.13/pipelines.html#chip

>How image is cropped in chip size multiple images from polygons ?

I don't understand the question.

>can i make my own datasets and use as training dataset in RV ?

You can, but only if the dataset is in the exact same format that the `chip` command for object detection produces.

**Comment by sagar1899** [comment]
> I don't understand the question.

if i have input images and GeoJson file contains polygons and my chip size is 300 then how that 300*300 train images is cropped from input images using polygons?

**Comment by AdeelH** [comment]
This is the relevant code that selects bounding boxes that overlap with a chip's window:

https://github.com/azavea/raster-vision/blob/d9d114054095ab837c29925f4db2e2d6ba62013e/rastervision_core/rastervision/core/data/label/object_detection_labels.py#L215-L232
