### ISSUE TITLE
Semantic_Segmentation

### ISSUE THREAD

**Issue by LinNiu** [azavea/raster-vision#1221]
![2021-07-25 15-33-34 的屏幕截图](https://user-images.githubusercontent.com/43545636/126891461-f58aa0b3-ff88-4d62-a908-6a28ec8f7712.png)
Hi! sir I want to test your code--'isprs_potsdam.py ' and load the data about it need,but the bug is taking place.
what is happending????

**Comment by AdeelH** [comment]
You're getting a `HTTP error 403: rate limit exceeded` when trying to download the model, which means that you have made too many requests in a short period of time. You should either wait for some time before running this again or you can add `-a external_model False` to the command you're using to run this example.

**Comment by LinNiu** [comment]
![2021-07-26 15-27-34 的屏幕截图](https://user-images.githubusercontent.com/43545636/126949669-1e7dcd56-7746-4d1c-9c8b-e6a4f916829c.png)
I add the "-a external_model False" .
my command is  
rastervision run local isprs_potsdam.py \
    -a raw_uri $RAW_URI -a processed_uri $PROCESSED_URI -a root_uri $ROOT_URI \
    -a test True -a external_model False --splits 2
please help me sir

**Comment by AdeelH** [comment]
The master branch is currently broken. Please use this branch: https://github.com/azavea/raster-vision/tree/v0.13.1

**Comment by LinNiu** [comment]
thank you sir!  I am trying.

**Comment by LinNiu** [comment]
![2021-07-28 09-40-04 的屏幕截图](https://user-images.githubusercontent.com/43545636/127249964-184866a7-659f-4e36-8f60-808182460e11.png)
![2021-07-28 09-40-26 的屏幕截图](https://user-images.githubusercontent.com/43545636/127249967-9dea0f19-8475-4ea2-9186-d19cce247aa8.png)
hi! sir the p1 is path to api web which code is 
class HTTPDefaultErrorHandler(BaseHandler):
    def http_error_default(self, req, fp, code, msg, hdrs):
        print("          ")
        print(req.full_url)
        raise HTTPError(req.full_url, code, msg, hdrs, fp)
I am printing the url.
I am never request your source 5000 times per hour.
so  What is  the matter???

**Comment by AdeelH** [comment]
I am not sure. Maybe someone else in your local network has been making too many requests to github.
