### ISSUE TITLE
Minimum System Hardware Requirenments for Raster Vision

### ISSUE THREAD

**Issue by sagar1899** [azavea/raster-vision#1223]
can you mention minimum hardware or software requirenments to run raster vision on local ?

Processor, RAM, GPU or any other minimum requirenments.

**Comment by AdeelH** [comment]
I don't believe there are any requirements as such. But if you want to use a GPU for training, you will need a CUDA-compatible GPU. Also, training on a CPU is very slow and not ideal for large datasets and models, so it is recommended to use a GPU.
