### ISSUE TITLE
Segmentation  Prediction:How to output multiple classes in vector label?

### ISSUE THREAD

**Issue by hengai** [azavea/raster-vision#1224]
I train with multiple classes in segmentation task，the prediction output of vector label have only one class while raster label have multiple classes.
Can the vector label output multiple classes?

**Comment by AdeelH** [comment]
Yes, indeed. You have to specify all the classes in the `vector_output` argument to `SemanticSegmentationLabelStoreConfig`. For example, in `isprs_potsdam.py`, to get vector labels for all classes, you can do:
```python
label_store = SemanticSegmentationLabelStoreConfig(
    rgb=True, vector_output=[PolygonVectorOutputConfig(class_id=i) for i in range(len(class_config])
```
This can probably be better documented though.
