### ISSUE TITLE
Raster Vision Dependencies Falling Out-of-date

### ISSUE THREAD

**Issue by mablem8** [azavea/raster-vision#1247]
## 🐛 Bug

The dependencies as described by the Ubuntu 16.04 [Dockerfile](https://github.com/azavea/raster-vision/blob/4eaa709ea4beeddded048fcbf670306d42262d9d/Dockerfile#L8) are falling out-of-date. Native installation of Raster Vision is not possible with the latest version of Ubuntu (20.04) without compiling some dependencies from source.

## To Reproduce

Native installation on Ubuntu 16.04 can be achieved using the following commands:
```bash
sudo apt install software-properties-common python-software-properties
sudo apt install wget=1.*
sudo apt install git=1:2.*
sudo apt install python-protobuf=2.*
sudo apt install python3-tk=3.*
sudo apt install jq=1.5*
sudo apt install build-essential
sudo apt install libsqlite3-dev=3.11.*
sudo apt install zlib1g-dev=1:1.2.*
sudo apt install libopencv-dev=2.4.*
sudo apt install python-opencv=2.4.*
sudo apt install unzip
sudo apt install curl
if [ ! -d "$HOME/Downloads" ]
then
  mkdir $HOME/Downloads
fi
cd $HOME/Downloads
wget https://repo.anaconda.com/miniconda/Miniconda3-4.7.12.1-Linux-x86_64.sh
bash Miniconda3-4.7.12.1-Linux-x86_64.sh -b
source $HOME/miniconda3/bin/activate
conda init
conda config --set auto_activate_base false
conda update -n base -c defaults -y conda
conda deactivate
sudo shutdown -r now
conda create -n "rv" python=3.6.13 -y
conda activate rv
conda install -c conda-forge gdal=3.0.4 -y
python3 -m pip install rastervision==0.13
```

These steps cannot be completed successfully on Ubuntu 20.04. Specifically, the following are not available:

```
python-protobuf=2.*
jq=1.5*
libsqlite3-dev=3.11.*
libopencv-dev=2.4.*
python-opencv=2.4.*
```

Also, it appears that some of these dependencies are not actually needed to install and use Raster Vision. The [Setup](https://docs.rastervision.io/en/0.13/setup.html#installing-via-pip) documentation glosses over native installation and could be updated to specify which dependencies are required.

## Expected behavior

A sequence of commands, located in the [Setup](https://docs.rastervision.io/en/0.13/setup.html#installing-via-pip) section of the documentation, to install Raster Vision and its dependencies natively on the latest version of Ubuntu.

## Environment

 - How you installed and are running Raster Vision: pip install
 - Raster Vision version or commit: 0.13
 - OS (e.g., Linux): Currently Ubuntu 16.04; would like to use Ubuntu 20.04 or later
 - Python version: Currently 3.6.13; would like to use the latest version
 - CUDA/cuDNN version if running on GPU: CPU only (does pip install support GPU execution?)

## Additional context

Raster Vision looks like a very promising and exciting project! Being able to use Raster Vision natively and outside of Docker is key to our use case. Currently, we can make limited use of Raster Vision on Ubuntu 16.04 after natively executing the relevant commands from the [Dockerfile](https://github.com/azavea/raster-vision/blob/4eaa709ea4beeddded048fcbf670306d42262d9d/Dockerfile) (there are some problems, described in a separate [issue](https://github.com/azavea/raster-vision/issues/1246)). However, due to the dependency version specifications, we cannot run Raster Vision on the latest version of Ubuntu (currently 20.04) without compiling many of the dependencies from source (arduous and not always an option). Looking at the dependencies listed in the Dockerfile, it appears that some of them are not needed anyway. Could the dependencies be culled and updated, and made explicit in the [documentation](https://docs.rastervision.io/en/0.13/setup.html#installing-via-pip)?

**Comment by mablem8** [comment]
Just to bump this: Ubuntu Linux 16.04 LTS reached the end of its five-year “Long Term Support” window in April 2021; Canonical no longer supports it beyond “Extended Security Maintenance.” See also the “Xenial Xerus” end-of-life [note](https://docs.docker.com/engine/install/ubuntu/) on Docker’s install page.

**Comment by lewfish** [comment]
I agree that it seems like a good idea to upgrade Ubuntu and the native dependencies, and remove the unused dependencies. I think it should be straightforward to remove or increment to the latest versions for most of these. However, I recently tried upgrading GDAL and rasterio and ended up making an issue because it was difficult https://github.com/azavea/raster-vision/issues/1211 

Have you made any progress on this? If you could get this to work I would be very happy to accept a PR. Otherwise, I might be able to take a stab at this in the next few weeks.

**Comment by lewfish** [comment]
> python-protobuf=2.*
> jq=1.5*
> libsqlite3-dev=3.11.*
> libopencv-dev=2.4.*
> python-opencv=2.4.*

I'm pretty sure that `python-protobuf` and `jq` are no longer needed. I'm not sure about `libsqlite3-dev` but it might be needed by Tensorboard. And OpenCV is needed: https://github.com/azavea/raster-vision/search?q=cv2 (although not a whole lot of it...)

> A sequence of commands, located in the [Setup](https://docs.rastervision.io/en/0.13/setup.html#installing-via-pip) section of the documentation, to install Raster Vision and its dependencies natively on the latest version of Ubuntu.

Good idea

**Comment by mablem8** [comment]
I have been able to run parts of Raster Vision 0.13 natively on Ubuntu 20.04 using the following steps:
```bash
# Python 3.7 on Ubuntu 20.04
sudo apt update
sudo apt upgrade
sudo apt install software-properties-common
sudo add-apt-repository ppa:deadsnakes/ppa
sudo apt update
sudo apt install python3.7 python3.7-dev python3.7-venv python3.7-tk

# Python 3.7 venv
python3.7 -m venv p3p7-env
source p3p7-env/bin/activate
$(pwd)/p3p7-env/bin/python3.7 -m pip install --upgrade pip
python3.7 -m pip install wheel
python3.7 -m pip install numpy==1.16.6
python3.7 -m pip install pillow==5.0.0
python3.7 -m pip install matplotlib==3.2.0
python3.7 -m pip install opencv-python==4.1.2.30
python3.7 -m pip install opencv-python-headless==4.1.2.30
python3.7 -m pip install rasterio==1.0.7
python3.7 -m pip install pystac==0.5.2
python3.7 -m pip install scikit-learn==0.19.2
python3.7 -m pip install rastervision==0.13
deactivate
```

It appears that Raster Vision 0.13 is not compatible with Python 3.8, which unfortunately is the only version of Python available for Ubuntu 20.04 without using something like the deadsnakes PPA. Under Python 3.8, OpenCV Python requires a version of numpy (>1.17) that is incompatible with the version of numpy (<1.17) required by some other dependency, making it impossible for pip to satisfy all dependencies simultaneously.

**Comment by jamesmcclain** [comment]
See also https://github.com/azavea/raster-vision/issues/1282

**Comment by psortos** [comment]
@mablem8 Were you able to get rastervision-pytorch-learner running on ubuntu 20.04?

**Comment by lewfish** [comment]
This issue is mostly resolved as of https://github.com/azavea/raster-vision/pull/1512 which updates the environment and most of the Python dependencies. The only part that is left is improving the setup docs to say how to install and use RV outside the Docker image we provide. So, I am closing this, and making a new issue to cover that https://github.com/azavea/raster-vision/issues/1542
