### ISSUE TITLE
Epoch Size Range

### ISSUE THREAD

**Issue by sagar1899** [azavea/raster-vision#1253]
What is the epoch size range in raster vision means what is maximum no of epoch ?
What is the relationship between no of epoch and training datasets ?

**Comment by AdeelH** [comment]
> What is the epoch size range in raster vision means what is maximum no of epoch ?

There is no limit on the number of epochs.

> What is the relationship between no of epoch and training datasets ?

You will have to clarify what you mean by "dataset" here. If you mean training scenes, then one epoch means one pass through the chips of all the training scenes. That is, if there are 3 training scenes with 100 chips each, then, in one epoch, all 300 chips will be passed through the model once.

**Comment by sagar1899** [comment]
> You will have to clarify what you mean by "dataset" here. If you mean training scenes, then one epoch means one pass through the chips of all the training scenes. That is, if there are 3 training scenes with 100 chips each, then, in one epoch, all 300 chips will be passed through the model once.

i mean datasets by "no of chips". then what is relationship between epoch and no of chips?

if i have less no of chips for training then what will be epoch size for better prediction?
and
if i have more no of chips for training then what will be epoch size for better prediction?
or for both epoch size is same for both?

**Comment by AdeelH** [comment]
The number of epochs is a hyperparameter the best value of which will vary depending on the dataset, model, and other hyperparameters. In general, however, training for too many epochs on a small dataset will lead to overfitting, and training for too few eopchs on a large dataset will lead to underfitting.
