### ISSUE TITLE
Extend support for external models and loss functions to the object detection task

### ISSUE THREAD

**Issue by AdeelH** [azavea/raster-vision#1256]
## 🚀 Feature

Support for external models and loss functions to the object detection task.

## Motivation

- #985 and #992 added the ability to use external model and loss function definitions for all tasks except for object detection because of its slightly more complex nature of the existing model architecture. However, it should still be possible for the user to use a different architecture if its inputs and outputs are compatible with the `ObjectDetectionLearner`.
- External model and loss function support is a significant RV feature and It would be nice to no longer have the not-for-OD caveat attached to it.

## Pitch

The `ObjectDetectionLearner` should make use of the external model and loss function configs if provided.

## Alternatives

N/A

## Additional context

Incorporating an external loss function might be tricky given that currently the loss in computed inside the model class.

**Comment by TekTes** [comment]
Hello Adeel, I have used rastervision object detection with a new dataset and the results are so far good. I am interested on this issue that you opened, which enables to apply different models outside resnet.

**Comment by AdeelH** [comment]
Thank you for your interest. We will try to prioritize this.

**Comment by TekTes** [comment]
Thank you Adeel, I appreciate your reply and for prioritizing this feature!
