### ISSUE TITLE
Run with GPU on local PC

### ISSUE THREAD

**Issue by sagar1899** [azavea/raster-vision#1270]
I have installed RV on local pc using pip command. my python version is 3.6.2.
i have Nvidia GeForce GTX 1080 ti gpu.

but when i run train command "python -m rastervision.pipeline.cli run_command H:\AIML\pipeline-config.json train"
the following warning is there. "WARNING:root:This caffe2 python run does not have GPU support. Will run in CPU only mode."

so how can i use RV train with GPU on local pc ?

**Comment by jamesmcclain** [comment]
I see from the drive letter that you are attempting to run on Windows?  To the best of my knowledge (and I am willing to take correction on this) RV has never been confirmed to work on Windows.

By way of Windows debugging, I would suggest as an initial step that you open a Python REPL and type
```pthon
import torch
torch.cuda.is_available()
```
to see if your installation of PyTorch can see your CUDA device.

With that having been said, my recommendation would be run the official docker images on Linux (preferably) or possibly on Windows (my understanding is that it is becoming possible to use CUDA devices from within Linux docker containers running in Windows, though we do not have direct experience with that).
