### ISSUE TITLE
NAME variable collides with WSL2 env variable in docker/run

### ISSUE THREAD

**Issue by jisantuc** [azavea/raster-vision#1274]
## 🐛 Bug

The docs say that `docker/run` should run a bash console in the pytorch container. However, in practice, it throws:

```bash
$ docker/run
docker: invalid reference format: repository name must be lowercase.
See 'docker run --help'.
```

## To Reproduce

1. Clone the repo (I'm at 7a473c5f)
1. Run `docker/build` and `docker/run`
1. Observe the error

## Expected behavior

Command doesn't throw

## Environment

Running Raster Vision directly in Windows is not supported, and we recommend that you run it from within a Docker container.

 - How you installed and are running Raster Vision (pip install on local vs. inside Docker image): cloned repo
 - Raster Vision version or commit: 7a473c5f
 - OS (e.g., Linux): WSL2 on Windows
 - Python version: n/a
 - CUDA/cuDNN version if running on GPU: n/a

**Comment by lewfish** [comment]
I cannot replicate this on Mac OS. Can you run `RASTER_VISION_DEBUG=1 docker/run` so we can see what command is being executed by the script?

**Comment by jisantuc** [comment]
Ha, didn't know that was an option, nice. For some reason it's running with the local network name of my computer:

```
docker run DESKTOP-DUKNSK6 --rm --ipc=host -it -v /home/james/.rastervision:/root/.rastervision -v /home/james/gitdirs/foss4g-groundwork-hitl-infra/raster-vision/:/opt/src/ -v /home/james/gitdirs/foss4g-groundwork-hitl-infra/raster-vision/data:/opt/data raster-vision-pytorch
```

**Comment by jisantuc** [comment]
Lemme also try on my mac, one sec

**Comment by jisantuc** [comment]
Ha ok I found out the problem -- there's a `$NAME` env var that's set by default in WSL2. If I force it to `''` everything works as expected.

**Comment by AdeelH** [comment]
>I can PR a note about this into docs if you'd like

Please do
