### ISSUE TITLE
Training image datatype

### ISSUE THREAD

**Issue by sagar1899** [azavea/raster-vision#1276]
can i use following datatype input image for training in object detection ?
1. Signed16
2. Signed32
3. Unsigned16
4. Unsigned32
5. Float32

**Comment by AdeelH** [comment]
Yes. You might also want to take a look at the [CastTransformer](https://github.com/azavea/raster-vision/blob/master/rastervision_core/rastervision/core/data/raster_transformer/cast_transformer_config.py).

**Comment by sagar1899** [comment]
when I take signed 16 datatype image as input, while running chip command all the chip images is generated is black.
So how can I use that as training images?

**Comment by AdeelH** [comment]
You can try using either
- the StatsTransformer to convert to uint8 (example: https://github.com/azavea/raster-vision/blob/master/integration_tests/chip_classification/config.py#L38-L41), or
- the CastTransformer to convert to float32

**Comment by sagar1899** [comment]
> You can try using either
> 
> * the StatsTransformer to convert to uint8 (example: https://github.com/azavea/raster-vision/blob/master/integration_tests/chip_classification/config.py#L38-L41), or
> * the CastTransformer to convert to float32

No, I'm talking about object detection.
Cowc_potsdam.py file.
In this functionality can I use other datatypes?

**Comment by AdeelH** [comment]
It is not limited to chip classification. You can use it in other tasks.

**Comment by sagar1899** [comment]
Thanks
