### ISSUE TITLE
Single Band Image Training

### ISSUE THREAD

**Issue by sagar1899** [azavea/raster-vision#1277]
I'm using single band image while training in object detection. Chips is generated of single band.but when i run train command the following error is shown.

x = torch.tensor(x).permute(2,0,1).float()/255.0
RuntimeError: number of dims don't match in permute

can i use single band image in object detection training ?

**Comment by AdeelH** [comment]
Object detection currently only works for 3-band images. 

If you want help with specific errors, you must use the bug report template and fill in all the information required.
