### ISSUE TITLE
Parallel Processing/ Threading while training.

### ISSUE THREAD

**Issue by sagar1899** [azavea/raster-vision#1285]
Can i use Parallel processing / Threading while training command to reduce training time ?

is raster vision is thread safe ?

**Comment by AdeelH** [comment]
Rastervision uses 4 worker processes by default for reading data during training. This is achieved by passing `num_workers=4` to `torch.utils.data.DataLoader` instances (https://docs.rastervision.io/en/0.13/api.html?highlight=workers#rastervision.pytorch_learner.DataConfig.num_workers). Please refer to the PyTorch documentation for `DataLoader` for details on how that works.
