### ISSUE TITLE
how to add a new pipeline or backbone to apply? such as, the framework has the resnet50, 101, mobilenet, alexnet, FCN ... and how to add the new unet, segnet..

### ISSUE THREAD

**Issue by yddcode** [azavea/raster-vision#1289]

**Comment by AdeelH** [comment]
>But when I used the model zoo of chip classification to predict, the predicted image is null, only yellow colour and square frame?

That is not enough information to debug your issue. Please use the bug report template to open a new issue and provide all the required details there.

>And what is the task flow of build segmentation? Is first chip classification and than semantic segmentation?

It is not clear to me what you are asking here.
