### ISSUE TITLE
How to make geojson for chip classification

### ISSUE THREAD

**Issue by sagar1899** [azavea/raster-vision#1320]
## ❓ Questions and Help

i want to train data in chip classification with vehicle and no vehicle class.
can you help me in making geojson label file ?
means that which attributes you have to provide while creating polygons..

**Comment by AdeelH** [comment]
>which attributes you have to provide while creating polygons..

You need to have a `class_id` or a  `class_name` or a `label` attribute.

Please see the file linked below for the actual code.

https://github.com/azavea/raster-vision/blob/fc181a6f31f085affa1ee12f0204bdbc5a6bf85a/rastervision_core/rastervision/core/data/vector_source/class_inference.py#L24-L56

**Comment by manapshymyr-OB** [comment]
@sagar1899 how did you create geojson for your dataset?

**Comment by sagar1899** [comment]
> @sagar1899 how did you create geojson for your dataset?

When creating vector theme you need to add attribute "class_name" which contains value like "Vehicle" or "no vehicle" and draw polygons and create geojson.
