### ISSUE TITLE
The Argument `img_channels` is required in `SemanticSegmentationImageDataConfig`, but in a Non-Obvious Way.

### ISSUE THREAD

**Issue by jamesmcclain** [azavea/raster-vision#1321]
## 🐛 Bug

The argument `img_channels` is required in `SemanticSegmentationImageDataConfig`, but in a non-obvious way.

## To Reproduce

I am try to create a pipeline to create chips from AVIRIS imagery, but I do not need it to do any work aside from that.  My declaration of the semantic segmenation data config object looks like this
```python
    data = SemanticSegmentationImageDataConfig(
        # img_channels=224,
        img_sz=chip_sz,
        num_workers=0,
        preview_batch_limit=8
    )
```
but I get an error saying that `img_channels` cannot be `None` regardless of whether the `img_channels` argument is directly supplied or not.  The error follows
```
 File "pydantic/main.py", line 274, in pydantic.main.BaseModel.__init__ 
pydantic.error_wrappers.ValidationError: 1 validation error for SemanticSegmentationImageDataConfig
img_channels
  none is not an allowed value (type=type_error.none.not_allowed)
```

The only way to circumvent this that I found was to supply an appropriately-sized list of channels to the raster source elsewhere in the pipeline
```python
    image_source = RasterioSourceConfig(
        channel_order=list(range(224)),
        uris=[imagery],
        allow_streaming=True,
        transformers=transformers,
        extent_crop=extent_crop,
    )
```

## Expected behavior

I would (possibly) expect that supplying `num_channels` to the data config would be sufficient, or alternatively the error message could be different.

## Environment

A docker container made from current (at time of writing) `master`.

**Comment by AdeelH** [comment]
Thanks for reporting. My initial guess is that this chunk of code is not working correctly https://github.com/azavea/raster-vision/blob/fc181a6f31f085affa1ee12f0204bdbc5a6bf85a/rastervision_core/rastervision/core/data/raster_source/rasterio_source.py#L136-L145

possibly because of the streaming or perhaps because of some peculiarity of the AVIRIS image. But I am not sure.
