### ISSUE TITLE
RV using GPU 

### ISSUE THREAD

**Issue by sagar1899** [azavea/raster-vision#1324]
can i get support of GPU in raster vision in linux ?

**Comment by AdeelH** [comment]
You do no need any extra configuration to make RV use the GPU. RV will automatically use the GPU if it detects it. If you are running inside the docker container, you can make the GPU available inside the container by passing the `--gpu` flag when starting the container, like so:
```sh
docker/run --gpu
```

Once inside the container, you can verify that the GPU is available by running 
```sh
nvidia-smi
```

**Comment by sagar1899** [comment]
> You do no need any extra configuration to make RV use the GPU. RV will automatically use the GPU if it detects it. If you are running inside the docker container, you can make the GPU available inside the container by passing the `--gpu` flag when starting the container, like so:
> 
> ```shell
> docker/run --gpu
> ```
> 
> Once inside the container, you can verify that the GPU is available by running
> 
> ```shell
> nvidia-smi
> ```

i'm using raster vision using pip installation (local RV) and not using docker container, so can i use GPU in python 3.6 version and raster vision 0.12 ?

**Comment by AdeelH** [comment]
All versions of RV should support GPUs.
