### ISSUE TITLE
Backend

### ISSUE THREAD

**Issue by sagar1899** [azavea/raster-vision#1326]
Can you please mention the backend of RV?
Means are rv using cnn or Faster cnn ?
Which convolution layers are rv uses?
Which regression method it uses?
Which model of torch that rv uses?

**Comment by AdeelH** [comment]
By default:
- Chip classification: ResNet
- Semantic segmentation: DeepLab with a ResNet backbone
- Object detection: FasterRCNN
- Regression: ResNet

For chip classification and semantic segmentation it is possible to use other architectures using the `ExternalModuleConfig`.

Please look at the code in the `rastervision_pytorch_learner` module for more details.
