### ISSUE TITLE
Error in loading bundle.zip from Model Zoo to perform predictions

### ISSUE THREAD

**Issue by theoway** [azavea/raster-vision#1338]
## 🐛 Bug

`rastervision.filesystem.filesystem.NotReadableError` is thrown when running the `predict` command on bundle.zip available from **Model Zoo**.  Tried it on [this](https://s3.amazonaws.com/azavea-research-public-data/raster-vision/examples/model-zoo-0.13/spacenet-rio-cc/model-bundle.zip) and [this](https://s3.amazonaws.com/azavea-research-public-data/raster-vision/examples/model-zoo-0.13/spacenet-vegas-buildings-ss/model-bundle.zip) bundle and I get the error in loading the `bundle.zip`.

## To Reproduce

1. Mount the local storage, with model-bundle.zip and raster(geotiff) files in them. I placed them in `opt/src/code/`
2. Run from path _/opt/src_ `rastervision predict code/model-bundle.zip code/raster.tif code/result.json` 
3. And I get this error: 
```
rastervision.filesystem.filesystem.NotReadableError: Could not read /tmp/tmph6zxrtcv/tmp8z0ovx7i/package/bundle_config.json
```
4. The same error occurred when I used `http` to get the bundle.zip. Using this command:
```
rastervision predict <link-to-bundle.zip> code/raster.tif code/result.json
```

## Expected behavior

It should be able to make predictions using the model-bundle.zip.

## Environment

**Docker container**, running image **quay.io/azavea/raster-vision:cpu-0.9**
Windows 10

**Comment by theoway** [comment]
@AdeelH Thanks for the prompt reply. Yeah, I can definitely use the latest version. Could you please tell me which branch/commit should I build my image on??
Also, I think we should add to documentation about compatibility issues with bundles.

**Comment by theoway** [comment]
@AdeelH Thanks! I think we can close this issue now.

**Comment by AdeelH** [comment]
> can you tell me how can I contribute to documentation. Just wanna add this thing about backwards compatibility for bundles.

It should probably go here: https://github.com/azavea/raster-vision/blob/master/docs/examples.rst#model-zoo

I think it should say that the bundles are only backward compatible down to version 0.12. Does that sound right, @lewfish?

**Comment by lewfish** [comment]
> I think it should say that the bundles are only backward compatible down to version 0.12. Does that sound right, @lewfish?

Sounds right to me.

**Comment by theoway** [comment]
> Sounds right to me.
Cool! I'll make a PR then 👍🏻
