### ISSUE TITLE
Docker image raster-vision:pytorch-0.13 fails to be deployed on Azure Container Instances

### ISSUE THREAD

**Issue by theoway** [azavea/raster-vision#1342]
## ❓ Questions and Help

This docker image cannot be deployed on Azure Container Instances: `quay.io/azavea/raster-vision:pytorch-0.13`
I'm using this ARM template:
```
{
    "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "resources": [
      {
        "name": "rv-resource-group",
        "type": "Microsoft.ContainerInstance/containerGroups",
        "apiVersion": "2019-12-01",
        "location": "southeastasia",
        "properties": {
          "containers": [
            {
              "name": "bytegis-test-rv",
              "properties": {
                "image": "quay.io/azavea/raster-vision:pytorch-latest",
                "resources": {
                  "requests": {
                    "cpu": 2,
                    "memoryInGb": 6
                  }
                },
                "ports": [
                  {
                    "port": 80
                  }
                ]
              }
            }
          ],
          "osType": "Linux",
          "ipAddress": {
            "type": "Public",
            "ports": [
              {
                "protocol": "tcp",
                "port": "80"
              }
            ],
            "dnsNameLabel": "bytegis-rv-demo"
          }
        }
      }
    ]
  }
```
It throws the error: 
`
Error: Failed to start container paulwx, Error response: to create containerd task: failed to mount container storage: guest modify: guest RPC failure: failed to mount container root filesystem using overlayfs /run/gcs/c/e51f86c414ae83c7c279a4252864a381399069d358f5d2303c97c630e17b049f/rootfs: no such file or directory: unknown
`
I even tried mounting Azure FIle Share folder to the container, but still throws the same error. Even without mounting, it is the same error.

## Steps to reproduce:
- Go to Azure portal and open Azure Container Instances form.
- Add the details and use this image
- Start the creation
- You'll see the container terminates after sometime, with this error. (This can be found in the `events` tab in the portal)
![Screenshot (91)](https://user-images.githubusercontent.com/41969735/153752076-52d637c2-ea63-4603-ba0e-2958b143b784.png)

## Additional notes:
Affected images:
- quay.io/azavea/raster-vision:pytorch-latest
- quay.io/azavea/raster-vision:pytorch-0.13

**Kindly let me know if this is a known issue. Shall I use a different image to use on Azure Container Instances?**

**Comment by lewfish** [comment]
I'm not familiar with this Azure service, but I would first verify that this problem is specific to the RV image you are trying to use. If you try to do this with a different image (like a generic Ubuntu image or something) do you still have the problem?

**Comment by theoway** [comment]
@lewfish I just tested with other images and Azure Containers work for them. Could anyone let me know if rastervision images are working fine(in AWS/DigitalOcean/Heroku etc.)? This way it can be confirmed if something's wrong with Azure Container for this particular image or there's something wrong in the image itself. Thanks for the help as always!

**Comment by lewfish** [comment]
I was just able to use `quay.io/azavea/raster-vision:pytorch-latest` on AWS Batch. So, it seems like this could be something more specific to Azure. I found this which might be related: https://docs.microsoft.com/en-us/answers/questions/635266/container-instances-are-failing-with-error-34-fail.html

**Comment by theoway** [comment]
That's what I found. Closing this issue 👍
