### ISSUE TITLE
How to set num_workers

### ISSUE THREAD

**Issue by sagar1899** [azavea/raster-vision#1362]
How can i set num_workers value in "cowc_potsdam.py" file for object detection ?

**Comment by AdeelH** [comment]
https://github.com/azavea/raster-vision/blob/51e4b30e6a4934ca04915145bc2db94ce5774def/rastervision_pytorch_backend/rastervision/pytorch_backend/examples/object_detection/cowc_potsdam.py#L125

https://github.com/azavea/raster-vision/blob/51e4b30e6a4934ca04915145bc2db94ce5774def/rastervision_pytorch_backend/rastervision/pytorch_backend/examples/object_detection/cowc_potsdam.py#L131

**Comment by sagar1899** [comment]
> https://github.com/azavea/raster-vision/blob/51e4b30e6a4934ca04915145bc2db94ce5774def/rastervision_pytorch_backend/rastervision/pytorch_backend/examples/object_detection/cowc_potsdam.py#L125
> 
> https://github.com/azavea/raster-vision/blob/51e4b30e6a4934ca04915145bc2db94ce5774def/rastervision_pytorch_backend/rastervision/pytorch_backend/examples/object_detection/cowc_potsdam.py#L131

I'm using raster-vision 0.12 is it same for that?
Because in rv 0.12  cowcpotsdam.py has no option for num workers.

**Comment by AdeelH** [comment]
Unfortunately, `num_workers` is not specifiable in version 0.12. It only became specifiable after #1008 which allowed you to set `num_workers` in the backend config. Since #1046 (that is version 0.13 and later), it is supposed to be set in the DataConfig like the examples above show.
