### ISSUE TITLE
How to proceed after pip install rastervision ?

### ISSUE THREAD

**Issue by Vijay-P1999** [azavea/raster-vision#1373]
Hi, I'm trying to do raster analysis on Tiff images. I came across RV, but the [quick start](https://docs.rastervision.io/en/latest/quickstart.html) didn't help. 
When i tried running this
> vijay@vijay:~/code/rastervision_core$ /bin/python3 /home/vijay/code/rastervision_core/rastervision/core/predictor.py
2022-03-31 12:43:57:rastervision.pipeline.rv_config: WARNING - Root temporary directory cannot be used: /opt/data/tmp. Using root: /tmp/tmpks15piyi
Traceback (most recent call last):
  File "/home/vijay/code/rastervision_core/rastervision/core/predictor.py", line 7, in <module>
    from rastervision.pipeline import rv_config
  File "/home/vijay/.local/lib/python3.8/site-packages/rastervision/pipeline/__init__.py", line 19, in <module>
    registry.load_plugins()
  File "/home/vijay/.local/lib/python3.8/site-packages/rastervision/pipeline/registry.py", line 236, in load_plugins
    discovered_plugins = {
  File "/home/vijay/.local/lib/python3.8/site-packages/rastervision/pipeline/registry.py", line 237, in <dictcomp>
    name: importlib.import_module(name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/vijay/code/rastervision_core/rastervision/core/__init__.py", line 5, in <module>
    from rastervision.core.data_sample import *
  File "/home/vijay/code/rastervision_core/rastervision/core/data_sample.py", line 5, in <module>
    from rastervision.core.data import Labels
  File "/home/vijay/code/rastervision_core/rastervision/core/data/__init__.py", line 4, in <module>
    from rastervision.core.data.raster_source import *
  File "/home/vijay/code/rastervision_core/rastervision/core/data/raster_source/__init__.py", line 5, in <module>
    from rastervision.core.data.raster_source.rasterio_source import *
  File "/home/vijay/code/rastervision_core/rastervision/core/data/raster_source/rasterio_source.py", line 13, in <module>
    import rasterio
  File "/home/vijay/code/rastervision_core/rasterio/__init__.py", line 11, in <module>
    from rasterio._base import gdal_version
ModuleNotFoundError: No module named 'rasterio._base'

rasterio._base is .pyc file in rasterio but couldn't import it for some reason. Dont know why.

Already tried:

1. Uninstalled and re-installed Rasterio, RV
2. Used RV repo instead of Pip3

Rasterio version used - [Click here](https://github.com/rasterio/rasterio)

Confused about how to proceed. **Can someone provide insights about how to proceed after installing raster-vision through pip3 ?**

**Comment by AdeelH** [comment]
To avoid any problems with dependencies, it is recommended to run Raster Vision from inside its Docker image. I would recommend following the quick start doc to get set up with Docker.

**Comment by sagar1899** [comment]
> Hi, I'm trying to do raster analysis on Tiff images. I came across RV, but the [quick start](https://docs.rastervision.io/en/latest/quickstart.html) didn't help. When i tried running this
> 
> > vijay@vijay:~/code/rastervision_core$ /bin/python3 /home/vijay/code/rastervision_core/rastervision/core/predictor.py
> > 2022-03-31 12:43:57:rastervision.pipeline.rv_config: WARNING - Root temporary directory cannot be used: /opt/data/tmp. Using root: /tmp/tmpks15piyi
> > Traceback (most recent call last):
> > File "/home/vijay/code/rastervision_core/rastervision/core/predictor.py", line 7, in 
> > from rastervision.pipeline import rv_config
> > File "/home/vijay/.local/lib/python3.8/site-packages/rastervision/pipeline/**init**.py", line 19, in 
> > registry.load_plugins()
> > File "/home/vijay/.local/lib/python3.8/site-packages/rastervision/pipeline/registry.py", line 236, in load_plugins
> > discovered_plugins = {
> > File "/home/vijay/.local/lib/python3.8/site-packages/rastervision/pipeline/registry.py", line 237, in 
> > name: importlib.import_module(name)
> > File "/usr/lib/python3.8/importlib/**init**.py", line 127, in import_module
> > return _bootstrap._gcd_import(name[level:], package, level)
> > File "/home/vijay/code/rastervision_core/rastervision/core/**init**.py", line 5, in 
> > from rastervision.core.data_sample import *
> > File "/home/vijay/code/rastervision_core/rastervision/core/data_sample.py", line 5, in 
> > from rastervision.core.data import Labels
> > File "/home/vijay/code/rastervision_core/rastervision/core/data/**init**.py", line 4, in 
> > from rastervision.core.data.raster_source import *
> > File "/home/vijay/code/rastervision_core/rastervision/core/data/raster_source/**init**.py", line 5, in 
> > from rastervision.core.data.raster_source.rasterio_source import *
> > File "/home/vijay/code/rastervision_core/rastervision/core/data/raster_source/rasterio_source.py", line 13, in 
> > import rasterio
> > File "/home/vijay/code/rastervision_core/rasterio/**init**.py", line 11, in 
> > from rasterio._base import gdal_version
> > ModuleNotFoundError: No module named 'rasterio._base'
> 
> rasterio._base is .pyc file in rasterio but couldn't import it for some reason. Dont know why.
> 
> Already tried:
> 
> 1. Uninstalled and re-installed Rasterio, RV
> 2. Used RV repo instead of Pip3
> 
> Rasterio version used - [Click here](https://github.com/rasterio/rasterio)
> 
> Confused about how to proceed. **Can someone provide insights about how to proceed after installing raster-vision through pip3 ?**

rastervision 0.12 uses rasterio 1.7 so install it properly.

**Comment by Vijay-P1999** [comment]
@sagar1899 Is it rasterio 1.7 or 1.1.7 ?
