### ISSUE TITLE
Quickstart guide is not Working. It returns a black image.

### ISSUE THREAD

**Issue by Vijay-P1999** [azavea/raster-vision#1374]
## 📚 Documentation

I followed every instructions mentioned in the [Quickstart](https://docs.rastervision.io/en/0.13/quickstart.html#id2) but when i run 
`> rastervision run local code/tiny_spacenet.py`
It works but the output is just a black image. 
You can get the tif file from [here](https://drive.google.com/file/d/1a8BgtO4J8Q9pJnf5lXp5NyHq_jveTwup/view?usp=sharing)
I even tried opening it in QGIS & Google Earth PRO. No changes.
Is the document out-dated ? @AdeelH

**Comment by AdeelH** [comment]
It looks like this in QGIS:
![image](https://user-images.githubusercontent.com/13014700/161212415-989471f3-0e48-4903-83bc-b2f362523ef2.png)

With the following layer display settings:
![image](https://user-images.githubusercontent.com/13014700/161212554-8b4ccd4d-65d8-40a6-a691-c26cd777ef3f.png)

Note that these are results from a minimal example and are not expected to be good. From the doc:
>but don’t get too excited! We trained a model for 1 epoch on a tiny dataset, and the model is likely making random predictions at this point. We would need to train on a lot more data for a lot longer for the model to become good at this task.

**Comment by Vijay-P1999** [comment]
@AdeelH I was aware that i can't expect good prediction results from 1 epoch training. I didn't knew that i need to tune these parameters you have mentioned above. **Thanks, i got the expected result which was shown in the quickstart guide**. And btw, where can i learn  about this parameter tunings? or is it a trial and error?. I could use those insights for my project.

**Comment by AdeelH** [comment]
I did not _need_ to tune any parameters in QGIS to get the raster to show up. I just changed it from the default gray to brighter colors so that's it's more easily visible. You can play around with these settings to find a good configuration as per your taste and/or visualization needs.
