### ISSUE TITLE
GPU Confusion

### ISSUE THREAD

**Issue by sagar1899** [azavea/raster-vision#1391]
i have two GPUs in my PC.
1. Nvidia Geforce RTX 1650 - 4 GB
2.  AMD Radeon - 512 MB

but when i run rastervision it will use AMD Radeon not using RTX 1650. can you please help me how to use RTX 1650 instead of AMD ?

**Comment by AdeelH** [comment]
Are you running inside the docker container?

**Comment by AdeelH** [comment]
Raster Vision uses the first device (according to whatever order `torch.cuda` uses) by default. To fix this, we can try to only expose one GPU to the command. To do this, we can set the `CUDA_VISIBLE_DEVICES` environment variable by adding it before the rastervision command.

One of these should do the trick:
```sh
 CUDA_VISIBLE_DEVICES="0" rastervision run ...
```
```sh
 CUDA_VISIBLE_DEVICES="1" rastervision run ...
```
