### ISSUE TITLE
Make Raster Vision easier to use as a library (and not just as a framework)

### ISSUE THREAD

**Issue by AdeelH** [azavea/raster-vision#1395]
## Problem
Raster Vision (RV) is a [framework](https://en.wikipedia.org/wiki/Software_framework). To use it, users must configure the RV pipeline by defining a `get_config()` function. This has the following disadvantages:
- Even the [simplest examples](https://docs.rastervision.io/en/0.13/quickstart.html#configuring-a-semantic-segmentation-pipeline) of these `get_config()` functions tend to be dozens of lines long.
- It is not obvious how to map user requirements to a suitable pipeline config without deep familiarity with RV internals.
- It is harder to debug because one cannot individually examine the various components of the pipeline to ensure that they are working as intended.
- Overriding RV default functionality requires creating [a new RV project](https://docs.rastervision.io/en/0.13/bootstrap.html?highlight=cookiecutter) which is a non-trivial amount of effort.

This high barrier-to-entry is likely discouraging for new users.

## Proposed solution
To remedy this, it is proposed that we refactor RV so that it is more easily usable as a library with multiple entry and exit points. This is in line with the general software engineering advice about [writing libraries instead of frameworks](https://www.brandons.me/blog/libraries-not-frameworks) as well as the [trajectory of other similar frameworks](https://ai.facebook.com/blog/reengineering-facebook-ais-deep-learning-platforms-for-interoperability/). 

A largely successful attempt to use RV (in its current state) as a library was made in [the companion notebook](https://colab.research.google.com/drive/1Ex5xbAx4epzReCQDsqvZLoTpF6AtfnHr?usp=sharing) to the [Change Detection blog](https://www.azavea.com/blog/2022/04/18/change-detection-with-raster-vision/).

An example of what a future workflow might look like:
![image](https://user-images.githubusercontent.com/13014700/165721385-19d6249d-d21e-4768-a7c3-17077f0f69d7.png)

## Tasks
To achieve this, we would need to complete the following tasks. Each of these should ideally be turned into its own issue.
- Ensure that RV is installable and usable outside of the Docker container.
- Ensure that classes can function without relying on global state (such as the global `tmp_dir`).
- ~Ensure that classes do not rely on Pydantic configs.~
- Simplify the initialization of a `GeoDataset` as much as possible. Currently, it requires first creating a `RasterSource`, a `LabelSource`, and a `Scene`. Can this be simplified? Is `Scene` a useful abstraction?
- Refactor `Learner`. 
- Make the `Learner` replaceable with custom training and prediction code.

**Edit:** Tasks are now being tracked here: #1460.

**Comment by pomadchin** [comment]
I feel like RV can and _should?_ be converted into a library, as indeed the configuration itself is a tough experience.

I'd like to suggest the _almost_ complete removal of RV Pipelines, and the same usecases can be reimplementated i.e. via [Kubeflow](https://www.kubeflow.org/docs/components/pipelines/sdk/python-function-components/); <- in this case RV will be used as a library, and Kubeflow will be used to orchestrate inputs / outputs / chain different steps together. 

The same can be probably achieved with Argo as well, depends on the needs and future requirements.

**Comment by lewfish** [comment]
An demo of running RV commands using Kubeflow graphs can be seen here: https://github.com/azavea/pipeline-playground/tree/main/kubeflow/rv

**Comment by cynthiahqy** [comment]
This would be a great enhancement. I'm interested in using rastervision in my research, but even getting the examples to run is quite complicated (esp. coming from R), and it's not clear how to integrate RV functionality with existing code

**Comment by lewfish** [comment]
> * It is harder to debug because one cannot individually examine the various components of the pipeline to ensure that they are working as intended.

Yeah, it reminds me of the old Tensorflow. Just define the computation graph and then let the system compile it and pray that it runs successfully.

**Comment by lewfish** [comment]
Overall, this sounds great, and I like the idea of keeping the notebook use case in mind. However, I'm not sure I agree with the part about "Ensure that classes do not rely on Pydantic configs." Some classes depend on a lot of hierarchical configuration, and re-using the Config classes is an easy way to accomplish this. Otherwise you might have constructors that take a very long list of arguments which is unwieldy. But, I don't have a very strong opinion -- it probably need to be judged on a case by case basis.

**Comment by lewfish** [comment]
It seems like the predictor and evaluation functionality should also be usable a la carte and within a notebook environment.

**Comment by AdeelH** [comment]
> It seems like the predictor and evaluation functionality should also be usable a la carte and within a notebook environment.

Yeah, prediction is next on my agenda. I'll share the refactoring plan here before jumping into it.
