### ISSUE TITLE
Issue with using the Predictor class for multi-class prediction vector output

### ISSUE THREAD

**Issue by xholmes** [azavea/raster-vision#1406]
## ❓ Questions and Help

If you have a usage or general question, you may ask it here or in our [Gitter Channel](https://gitter.im/azavea/raster-vision). 

**Please check our [documentation](https://docs.rastervision.io/en/latest/index.html) first.**

If you want help with an error, please use the bug report template instead and fill in all the details.

Low-effort posts that are unclear, lack details, or are poorly formatted might be closed without a response.

---
Hi,
First off, great work on developing and bringing RasterVision till its current state. Its a promising and awesome tool!

I had managed to trained a multi-class Semantic Segmentation model to predict on aerial imagery. Now, I am trying to use the trained model bundle to predict on multiple new images. I am expecting it to generate an output label tiff and 4 vector label files, 1 for each class. I had written a script that uses the `Predictor` class to allow me to load the model once and predict on new batches of images.  However, the script seems to just "hangs" there after it outputs the first vector file. 

When i tried to use the same steps and code to train a separate model but just predicting on one class (i.e., generate one vector output only) and use the same `Predictor` script, it works perfectly for what I intended to do (load model once, predict on multiple images).

Following is my code for how i configure my label store during **model training**:
```
    def make_scene(id) -> SceneConfig:
        # Setup the configuration for each image
        img_name = os.path.join(data_uri, '{}_raster.tif'.format(id))
        label_name = os.path.join(data_uri, '{}_label.geojson'.format(id))

        raster_source = RasterioSourceConfig(uris=[img_name],
                                             channel_order=channel_order)
        vector_source = GeoJSONVectorSourceConfig(uri=label_name,
                                                  default_class_id=0,
                                                  ignore_crs_field=True)

        # Rasterise the GeoJson vector labels to fit Semantic Seg. requirements
        label_source = SemanticSegmentationLabelSourceConfig(
            raster_source=RasterizedSourceConfig(
                vector_source=vector_source,
                rasterizer_config=RasterizerConfig(background_class_id=0,
                                                   all_touched=True))
        )
        # Set the output to be in vector output
        label_store = SemanticSegmentationLabelStoreConfig(
            rgb=True, vector_output=[PolygonVectorOutputConfig(class_id=1),
                                     PolygonVectorOutputConfig(class_id=2),
                                     PolygonVectorOutputConfig(class_id=3),
                                     PolygonVectorOutputConfig(class_id=4)])

        return SceneConfig(id=id, raster_source=raster_source,
                           label_source=label_source, label_store=label_store)

    # Compile the input scene configurations
    scene_dataset = DatasetConfig(
        class_config=class_config,
        train_scenes=[make_scene(id) for id in train_id],
        validation_scenes=[make_scene(id) for id in val_id]
    )
```

Following is my code for the prediction script using the `Predictor` class.
```
import sys
import os
import time
import argparse
import shutil
from rastervision.core import Predictor

if __name__ == '__main__':
    # Get arguments
    parser = argparse.ArgumentParser(description='Script to utilise a RV model bundle for '
                                                 'predicting building footprints using '
                                                 'semantic segmentation')
    parser.add_argument('-m', help='URI pointing to RV model bundle for semantic segmentation')
    parser.add_argument('-i', help='Input image folder URI.')
    parser.add_argument('-o', help='URI to folder for storing output of prediction')
    parser.add_argument('-t', help='Folder to store tmp data')

    args = parser.parse_args()

    # Construct the list of images to predict on. Currently only accepts
    # GeoTIFFs. Note: RV assumes all images are in EPSG:4326
    img_list = [os.path.join(args.i, i) for i in os.listdir(args.i)
                if i.endswith('.tif')]

    if len(img_list) == 0:
        print('There are no valid images for prediction in the image folder.')
        sys.exit(2)

    # Initialise the predictor with the RV model bundle
    t_start = time.perf_counter()
    predictor = Predictor(args.m, args.t)
    print("Model loaded in {}".format(time.perf_counter() - t_start))

    label_format = '{}_label.tif'
    vector_format = '{}_{}_vector.json'
    predict_tif = os.path.join(args.o, 'labels.tif')
    predict_vector_path = os.path.join(args.o, 'predict')

    # Run predict on one image at a time
    o_start = time.perf_counter()
    for img in img_list:
        t_start = time.perf_counter()
        predictor.predict([img], args.o)
      
        # Had some other code here to save the outputs to a separate folder to 
       # prevent output from being overwritten, just in case

    # Finish predictions
    print('All predictions completed in {}'.format(time.perf_counter() - o_start))

```

Appreciate your insights on what i had done wrongly or issues here!

**Comment by xholmes** [comment]
With regards to the "errors" i am seeing on the console:

The prediction script just stops halfway:
![Screen Shot 2022-05-11 at 9 07 12 AM](https://user-images.githubusercontent.com/6213484/167722408-19d2fa79-0f6e-46ad-9548-b444bc5aa36a.png)

I am just seeing the following files in my output folder:
![Screen Shot 2022-05-11 at 9 07 45 AM](https://user-images.githubusercontent.com/6213484/167722474-c85058a6-990f-4c5e-bd5f-16ec56ddbf9e.png)

In the `predict` folder ...
![Screen Shot 2022-05-11 at 9 08 52 AM](https://user-images.githubusercontent.com/6213484/167722481-aa093cd4-e23c-463d-9fc9-ae6a3d944b4b.png)

I can see all 4 classes (red, blue, green, grey) being predicted in the `labels.tif` file:
![Screen Shot 2022-05-11 at 9 15 00 AM](https://user-images.githubusercontent.com/6213484/167723096-e259d068-66dd-43bf-a3c6-f83b9dc9fb39.png)

**Comment by AdeelH** [comment]
Hi, can you share which version of Raster Vision you are using and whether you are running it inside the docker container?

**Comment by AdeelH** [comment]
Also, since it seems to get stuck when creating vector output for class_id = 2, can you try excluding `PolygonVectorOutputConfig(class_id=2)` from the list and see if the rest work fine?

**Comment by xholmes** [comment]
Hi @AdeelH ,

Thank you for your reply.

> Hi, can you share which version of Raster Vision you are using and whether you are running it inside the docker container?
I am using 0.13 and running it inside a singularity container. I had built a docker container to CUDA 11 and converted it into a singularity container as that is what we are using.

> Also, since it seems to get stuck when creating vector output for class_id = 2, can you try excluding PolygonVectorOutputConfig(class_id=2) from the list and see if the rest work fine?

Do you mean converting my training script to output just 1 class_id as vector output and running the prediction script again using the resulting bundle? I had tried that with just predicting on one class and that works. (but i used `class_id=0` for my PolygonVectorOutputConfig due to the order of my label class name list.)

**Comment by xholmes** [comment]
I quickly adjusted my training script to predict on 4 classes, but set it to only generate a vector output for the 1st class label (class_id=1). Running the resulting model_bundle worked with my script.  

Seems to be an issue when asking the predictor to generate more than 1 class vector output.

**Comment by xholmes** [comment]
> Yes, I was suggesting something like that. You might even want to try generating vector output for all classes except the second one to see if the problem is with that class specifically. Like so:

Tested the script and bundle as you suggested. That worked. Your speculation seems to be right that the large scattered regions of the output mask is causing the halt. Not sure if it is taking very long or something. Will try to figure out something on my side.

Thank you for your help @AdeelH !

Will close this comment.

**Comment by AdeelH** [comment]
Glad we figured it out! Out of curiosity, what are the dimensions of the raster that you are predicting over?

**Comment by xholmes** [comment]
For the image i was testing with, it is around 13340 x 8899 pixels. The entire area is slightly larger though, but not sure of what the entire area's resolution is.

**Comment by AdeelH** [comment]
I see. If you want to look more into this, RV uses rasterio, specifically [rasterio.features.shapes](https://rasterio.readthedocs.io/en/latest/api/rasterio.features.html#rasterio.features.shapes) to polygonize rasters.
