### ISSUE TITLE
Predict on a custom image gives back a black tif

### ISSUE THREAD

**Issue by gmommi** [azavea/raster-vision#1409]
## Help

I used this command rastervision predict https://s3.amazonaws.com/azavea-research-public-data/raster-vision/examples/model-zoo-0.13/spacenet-vegas-buildings-ss/model-bundle.zip /opt/src/image.tif output .
I uploaded my custom image in the docker container and copied the predictions to my local machine. I opened it on QGIS but it's all gray.
I tried on https://s3.amazonaws.com/azavea-research-public-data/raster-vision/examples/model-zoo-0.12/spacenet-vegas-buildings-ss/1929.tif as well and buildings footprint segmentation worked.
Below the predictions I got on my image.
Please help me! :D
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/90242432/170068828-560d447b-2347-4c16-a197-67a7425ab14f.png)

**Comment by AdeelH** [comment]
Hi. Can you try again with this model bundle: https://azavea-research-public-data.s3.amazonaws.com/raster-vision/examples/model-zoo-0.12/spacenet-vegas-buildings-ss/model-bundle.zip

and see if that works better?

**Comment by gmommi** [comment]
Thank you for your reply but using this model bundle https://azavea-research-public-data.s3.amazonaws.com/raster-vision/examples/model-zoo-0.12/spacenet-vegas-buildings-ss/model-bundle.zip I got this error:
**File "/opt/src/rastervision_pytorch_backend/rastervision/pytorch_backend/pytorch_semantic_segmentation_config.py", line 33, in ss_learner_backend_config_upgrader
if data_cfg_dict['img_sz'] is None:
KeyError: 'img_sz'**

How can I solve the problem?

**Comment by AdeelH** [comment]
> Thank you for your reply but using this model bundle https://azavea-research-public-data.s3.amazonaws.com/raster-vision/examples/model-zoo-0.12/spacenet-vegas-buildings-ss/model-bundle.zip I got this error:
> **File "/opt/src/rastervision_pytorch_backend/rastervision/pytorch_backend/pytorch_semantic_segmentation_config.py", line 33, in ss_learner_backend_config_upgrader if data_cfg_dict['img_sz'] is None: KeyError: 'img_sz'**

That's a bug. I have created a fix here: #1411.

Which version of Raster Vision are you using? And how i.e. `pip` or downloaded docker image or docker image built from source?

**Comment by gmommi** [comment]
Thank you. I've now created a docker container with this image **quay.io/azavea/raster-vision:pytorch-0.12** .
Performance is not that good. This is what I get:
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/90242432/170471412-98fdab0a-94c3-4506-88ce-1abd89ba53ed.png)
 Any suggestion to improve the performance?

**Comment by AdeelH** [comment]
The model is expected to do worse on a new dataset. If you have some labels for this new dataset, you can try to fine-tune the model on it or train a new model from scratch on it. See also the discussion in #1396.
