### ISSUE TITLE
GPU Usage for predict command for Object Detection

### ISSUE THREAD

**Issue by sagar1899** [azavea/raster-vision#1410]
i'm running rv 0.12 for object detection and i have input image with 6000*6000 dimension and chip size is 300*300. so can you give understanding of how many of this parameters can be store in gpu?

how gpu is used in predict command?

can you explain gpu usage ?

if my parameters change how to find estimated gpu memoty usage?

**Comment by sagar1899** [comment]
can someone help me?

**Comment by AdeelH** [comment]
The chip size used during prediction is specified by the `predict_chip_sz` option: https://github.com/azavea/raster-vision/blob/1cecdf914b60629f8cad6feead3fdd153cf6be59/rastervision_pytorch_backend/rastervision/pytorch_backend/examples/object_detection/cowc_potsdam.py#L80.

You can check GPU utilization while the prediction is running using the `nvidia-smi` command.

See also this note about object detection prediction performance: https://github.com/azavea/raster-vision/blob/1cecdf914b60629f8cad6feead3fdd153cf6be59/rastervision_core/rastervision/core/rv_pipeline/object_detection.py#L143-L149

**Comment by sagar1899** [comment]
i want to know which part can use GPU?

if i change my image size and chip size how many gpu memory will be used?
