### ISSUE TITLE
Noobie help on satellite dataset

### ISSUE THREAD

**Issue by gaussiangit** [azavea/raster-vision#1418]
I am planning to build a custom dataset using satellite images for segmentation task.
My approach is to build dataset using OSM + QGIS Satellite view .
Can anyone tell me how much dataset (tifs) is required ? 
Also how can I fine tune the segmentation model on the custom class that I have using raster vision ?

**Comment by AdeelH** [comment]
> Can anyone tell me how much dataset (tifs) is required ?

There is no one-size-fits-all answer to this, but in general, your data should be as representative of the kinds of images that you want to use it for. As a general rule-of-thumb, however, it is recommended to have at least several hundred, and ideally several thousand, training chips. The number of training chips will depend on the size of your raster (TIFF), your chip size, and your chip sampling strategy.

> Also how can I fine tune the segmentation model on the custom class that I have using raster vision ?

You can see an example of training a semantic segmentation model here: https://github.com/azavea/raster-vision/blob/0.13/rastervision_pytorch_backend/rastervision/pytorch_backend/examples/semantic_segmentation/isprs_potsdam.py

Can you clarify what you mean by "fine tune"? If you want to start training from pretrained weights, then yes, that is possible.
