### ISSUE TITLE
Modify cloudformation template to allow use of EC2 instances as well

### ISSUE THREAD

**Issue by theoway** [azavea/raster-vision#1469]
## 🚀 Feature
Updating the `cloudformation template` so that it allows to use `EC2` for CPU & GPU ComputeEnvironment as well. Currently, it is fixed at using `SPOT` instances. 

## Motivation
When working with batch, many times Spot instances are not available for `P` instances, which prevents GPUComputeEnvironment from being deployed, resulting in stuck jobs.

## Alternatives
Manually update the cloudformation template.

## Additional context
See this gitter thread(I didn't know how to add chat link here 😊): 
![Screenshot (149)](https://user-images.githubusercontent.com/41969735/188009586-1a458ec1-040a-464c-9137-a6a912d40b35.png)

**Comment by theoway** [comment]
I'd make a PR for this 👍

**Comment by AdeelH** [comment]
Thanks for looking into this. I think defining a new compute environment and adding it to the existing job queue makes sense.

CC @lewfish

**Comment by lewfish** [comment]
> Thanks for looking into this. I think defining a new compute environment and adding it to the existing job queue makes sense.

I agree. It looks like the `ComputeEnvironmentOrder` field can be used to place the on demand environment at a lower priority.
