### ISSUE TITLE
the segmentation task stops by throwing out a stopIteration

### ISSUE THREAD

**Issue by helxsz** [azavea/raster-vision#151]
i am using 'tnation/batch-job-termination' version for the segmentation task on the isprs/vaihingen dataset.

here is my configuration file

```
{
    "batch_size": 8,
    "git_commit": "c96f87",
    "dataset_name": "isprs/vaihingen",
    "generator_name": "image",
    "active_input_inds": [0, 1, 2],
    "use_pretraining": false,
    "freeze_base": false,
    "nb_epoch": 150,
    "init_lr": 1e-5,
    "optimizer": "adam",
    "target_size": [256, 256],
    "eval_target_size": [2000, 2000],
    "model_type": "fcn_resnet",
    "train_ratio": 0.8,
    "nb_val_samples": 512,
    "run_name": "4_5_17/fcn_resnet_all_scratch_low_lr",

    "samples_per_epoch": 4096,
    "problem_type":"semseg",
    "epochs":"80000",
    "steps_per_epoch":"100",
    "validation_steps":"20"
}
```

when training the model, the training only takes less than a minute, then throws out a StopIteration exception 

        self.dev_file_inds = [1, 3, 5, 7, 11, 13, 15, 17, 21, 23, 26, 28, 30, 32, 34, 37]
            
the cooresponding code is found [here](https://github.com/azavea/raster-vision/blob/feature/tnation/batch-job-termination/src/rastervision/common/data/generators.py)

that when the images are all scanned over and sending all the batch, the code will stop through StopIteration. 

```
    def make_img_batch_generator(self, file_inds, target_size, batch_size,
                                 shuffle, sample_probs=None):
        def make_gen():
            if shuffle:
                return self.make_random_img_generator(
                    file_inds, target_size, sample_probs)
            return self.make_img_generator(file_inds, target_size)
        gen = make_gen()
        while True:
            batch, batch_file_inds = self.get_samples(gen, batch_size)
            if batch is None:
                raise StopIteration()
            yield batch, batch_file_inds
```

Of course the training should be going on for hours and the code seems to be all right, but still I don't know how to fix it.

**Comment by lewfish** [comment]
Sorry I didn't reply to this. The current code for segmentation is deprecated and unsupported. Soon we will be refactoring Raster Vision and eventually adding back in semantic segmentation functionality.
