### ISSUE TITLE
Query is invisible in interactive docs search 

### ISSUE THREAD

**Issue by lewfish** [azavea/raster-vision#1555]
## 🐛 Bug

When I search for something in the docs using the new interactive search bar it seems to work except the query is not visible in the search box. Instead a bunch of dots appear. This was in Chrome Version 107.0.5304.110 (Official Build) (arm64) with the extension turned off.

![Screen Shot 2022-11-14 at 12 40 05 PM (2)](https://user-images.githubusercontent.com/1896461/201729357-53cc9725-0327-413c-91da-979dac0ea7e4.png)

**Comment by lewfish** [comment]
@AdeelH

**Comment by AdeelH** [comment]
Doesn't happen on `Version 106.0.5249.103 (Official Build) (64-bit)` but does on an updated Chrome (don't have the version on hand) and Firefox `106.0.5 (64-bit)`.

Also, it doesn't seem like the down-ranking of source-code pages is working.
