### ISSUE TITLE
Same explanation for SlidingWindowGeoDataset and RandomWindowGeoDataset

### ISSUE THREAD

**Issue by ammarsdc** [azavea/raster-vision#1567]
## 📚 Documentation

> The SlidingWindowGeoDataset allows reading the scene by sampling random window sizes and locations.

This description is same to explained both SlidingWindowGeoDataset and RandomWindowGeoDataset. This can be found here: https://docs.rastervision.io/en/latest/tutorials/sampling_training_data.html

**Comment by AdeelH** [comment]
You are right. Thanks for catching that!
