### ISSUE TITLE
Capture resources for Batch environment creation in Terraform

### ISSUE THREAD

**Issue by tnation14** [azavea/raster-vision#163]
Encapsulate the creation of the `raster-vision-cpu` and `raster-vision-gpu` Batch environments in Terraform.

See:
- https://github.com/azavea/raster-foundry-deployment/pull/94
- https://github.com/azavea/raster-foundry-deployment/pull/96
- http://docs.aws.amazon.com/batch/latest/userguide/IAM_policies.html

**Comment by lossyrob** [comment]
This is fixed by https://github.com/azavea/raster-vision-aws
