### ISSUE TITLE
Automatically shift raster semantic segmentation labels with different extent than imagery

### ISSUE THREAD

**Issue by lewfish** [azavea/raster-vision#1739]
When using raster-based semantic segmentation labels with imagery that has a different spatial extent, the chips will be read incorrectly because RV is not accounting for the different frames of reference. The pixel-based coordinates for the image chip will be used to crop out the labels which is not what the user would expect. This is a feature request bordering on a bug report since the behavior is so counterintuitive.

An example of this situation can be found in [this notebook](https://github.com/lewfish/nyc-land-cover/blob/1a527548415f83c481328e5aee0bce4255210a54/notebooks/nyc.ipynb) in which the labels for a whole city are in a single file while the imagery has been divided into smaller chips. To work around this, the `extent` is explicitly set for the `RasterioSource` for the labels. 

Perhaps this situation could be detected automatically, and the extent of the labels could be set based on the imagery.

**Comment by AdeelH** [comment]
l'm leaning towards something like this:

```py
class Scene:
    def __init__(self, ...):
        ...
        extent_pixel_label = ...
        self.label_source = label_source.crop(extent_pixel_label)
        ...
```
