### ISSUE TITLE
Some tiles get incorrect when predicting but of 95% are ok 

### ISSUE THREAD

**Issue by greenhawktobias** [azavea/raster-vision#1776]
I'm working in a project predicting urban tree canopy cover in the a municipality (Helsingborg in Sweden).

**We are using**
Raster vision v.0.13 within a Docker container
R,G,B, ELEVATION (4 channel raster)

I did this a couple of times so I'm quite familiar with everything. Everything went fine without error message, both training and
predictions. But somehow some of the most western tiles closest get strange predictions, both shifted and totally incorrect. Only the tiles far west also (that's a strange logic?)

My first theory was that the elevation data was corrupt, but indata looks correct (both data and crs) so it must be something with the prediction itself (even if it gets correct for ~95% of the tiles.

Any idea what can be wrong?

Blue outline shows incorrect prediction and red outline correct predicton,

![predictions](https://user-images.githubusercontent.com/79131575/232122762-85bdf48f-814b-4866-9e01-f59672eb18f0.PNG)

**Comment by lewfish** [comment]
That is strange. Are you sure the imagery you are viewing is what the model was run on? I'm wondering if maybe the scene was made up of multiple GeoTIFFs, and the GeoTIFF near the red circled area matches the imagery in QGIS, and and the GeoTIFF near the blue circled area is misaligned.

**Comment by lewfish** [comment]
I wasn't sure what was going on in https://github.com/azavea/raster-vision/issues/1773 but maybe they could be related.

**Comment by greenhawktobias** [comment]
I am guiding a group of gis-engineers to do something similar I did in my municipality. I don't have the orthoimages myself(a lot of GB), therefore using Google satellite imagery to visualise the results. But I helped them in the process and I have all the predictions. All data was trained an predicted on ortho imagery and elevation data from 2022.

**Comment by lewfish** [comment]
Which version of RV are you using? Would you be able to share the model bundle and a sample image where this is happening?

**Comment by greenhawktobias** [comment]
We are using RV 0.13. We had some busy conference days, but will upload the files next week.

**Comment by lewfish** [comment]
Thanks for the data. We are having a busy week, but will try to look into this next week.

**Comment by AdeelH** [comment]
@greenhawktobias Can you share the model bundle produced by the `bundle` command instead? The one that can be used with the `predict` command. Please also share the config file that produced the model.

>But somehow some of the most western tiles closest get strange predictions, both shifted and totally incorrect. Only the tiles far west also (that's a strange logic?)

Can you also explain in more detail what the problem is? You trained a building segmentation model and the when you overlay the results on top of Google satellite imagery (which is identical to the imagery used to produce the results), the results seem misaligned; is that right?

**Comment by greenhawktobias** [comment]
@AdeelH We double checked the mosaic process in FME. The predictions were correct but something happens when we merge the tiles in FME (GIS desktop software) and some tiles becomes misaligned. The problem is therefore not in Raster Vision. Thanks for your time and concern withy this. :-)
