### ISSUE TITLE
Classification training gets stuck at epoch 0 when using batch

### ISSUE THREAD

**Issue by infinitone** [azavea/raster-vision#181]
When i use the AWS batch method for a classification job such as:
 ```
python -m rv.utils.batch develop "python -m rv.classification.cowc.train s3://infinitone/classification/configs/cowc-potsdam.json \
s3://infinitone/classification/training-data/cowc-potsdam-train.zip s3://infinitone/classification/training-data/cowc-potsdam-test.zip \
s3://infinitone/classification/trained-models/cowc-potsdam" --attempts 1 
```

Everything works fine, it boots up a p2.xlarge instance and job starts fine until it just prints `train epoch 0` and never proceeds, i waited 2 hours and nothing:
![image](https://user-images.githubusercontent.com/2072309/34967797-214a2a4e-fa1a-11e7-9c30-af8287d9cce4.png)

I noticed that the python worker functions are defunct when doing `ps aux`.  Here is my config json:
```
{
    "arch": "resnet18",
    "workers": 4,
    "epochs": 50,
    "batch_size": 64,
    "image_size": 256,
    "dataset": "folder",
    "lr": 0.1,
    "momentum": 0.9,
    "weight_decay": 1e-4,
    "print_freq": 10,
    "pretrained": true,
    "topK": [1, 1],
    "mean": [36, 38, 35],
    "std": [16, 15, 15],
    "num_classes": 2
}
```
Anyone else having similar issue?  Is my config.json correct?

Only way i got it to work was to use workers=0 but then its really slow...

**Comment by lewfish** [comment]
I could also only get it to work with workers=0, and I think this is due to the same underlying problem that is causing https://github.com/azavea/raster-vision/issues/168. I haven't had a chance to look into it too deeply, but I think it's related to https://github.com/pytorch/pytorch/issues/1355

**Comment by lewfish** [comment]
We're not using Pytorch at the moment and there's a good chance this problem has been fixed in more recent versions of Pytorch, so I'm closing this.
