### ISSUE TITLE
Configure config files to be optimized for aerial imagery

### ISSUE THREAD

**Issue by jhovell** [azavea/raster-vision#185]
Looks like this might not be the principal focus of this library, but does it make any sense to provide more reasonable defaults for aerial imagery datasets? I took a look at [these config files](https://github.com/azavea/raster-vision/tree/develop/src/config-samples/detection/train
), which appear to be nearly identical to what is provided from Tensorflow.

I saw there was a closed issue regarding [tuning hyperparameters for small objects](https://github.com/azavea/raster-vision/issues/155), but didn't see where that was reflected in the code base.

I don't have a ton of background in ML and am just starting to learn Tensorflow object detection, but I saw this [note in this blog post](https://towardsdatascience.com/how-to-train-your-own-object-detector-with-tensorflows-object-detector-api-bec72ecfe1d9) :

>Note: The data_augmentation_option is very interesting if your dataset doesn’t have much of variability like different scale, pose etc.. A full list of options can be found here (see PREPROCESSING_FUNCTION_MAP).

Or if this isn't really applicable to this project, do you happen to know any suggested parameter settings or models for processing aerial imagery or areas to read up in?

**Comment by lewfish** [comment]
I am currently rewriting RV and there is a new config format. I will post a new README in the next few days that will have a sample configuration that should work well.

**Comment by lewfish** [comment]
The object detection tutorial now has a sample workflow for the COWC dataset that should work reasonably well. More work will be needed to get the best performance including using a model that is more accurate than Mobilenet. We will be running more exhaustive experiments over the next few months and will document them.
