### ISSUE TITLE
ARM64 build currently broken

### ISSUE THREAD

**Issue by jamesmcclain** [azavea/raster-vision#1867]
## 🐛 Bug

The ARM64 docker image appears to be broken.  On the following configuration,
```
$ docker --version
Docker version 24.0.5, build ced0996
$ uname -a
Linux XXX #26~22.04.1-Ubuntu SMP Mon Apr 24 01:58:03 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux
```
I get this while trying to build:
```
3.713 ERROR: Could not find a version that satisfies the requirement onnxruntime-gpu==1.15.0 (from versions: none)
3.713 ERROR: No matching distribution found for onnxruntime-gpu==1.15.0
```
There does not seem to be an `onnxrutnime-gpu` package for ARM64.

I does not seem possible to resolve the dependency on `triangle`, either (the native code does not build on ARM).

## To Reproduce

1. Start up a Graviton instnace on AWS
2. [Install the latest docker](https://docs.docker.com/engine/install/ubuntu/)
3. Attempt to build the docker image

## Expected behavior

A successful build

## Environment

A Graviton instance on AWS.

**Comment by AdeelH** [comment]
A solution might be to declare these as optional dependencies: https://setuptools.pypa.io/en/latest/userguide/dependency_management.html#optional-dependencies and add some exception handling around their imports.

**Comment by jamesmcclain** [comment]
Sorry for closing it, :rofl:
