### ISSUE TITLE
Link in README.md 404s

### ISSUE THREAD

**Issue by jasonharrison** [azavea/raster-vision#188]
https://github.com/azavea/raster-vision/blob/develop/README.md contains:

```
### Running object detection scripts

See the [object detection README](src/detection/README.md).
```

However, https://github.com/azavea/raster-vision/blob/develop/src/detection/README.md 404s.

**Comment by lewfish** [comment]
I will add a new README in the next few days after I am finished rewriting RV. Thanks for the heads up.

**Comment by lewfish** [comment]
The new README should have links that work now with new content.
