### ISSUE TITLE
Improve object detection sample workflow

### ISSUE THREAD

**Issue by lewfish** [azavea/raster-vision#199]
Currently, the object detection sample workflow isn't very useful because it uses relatively large files which take a long time to run the workflow on and the predictions are garbage since the model was only trained for 5 steps. Here are steps towards making the sample workflow more useful. If we do this, it will also lay the foundation for an automated integration test.

- [x] Make separate model repo to store pretrained model files as Releases since they are large files.  This is how Keras distributes model files.
- [x] Release a decent car detection model.
- [x] Create smaller test GeoTIFF files from the Potsdam imagery, release them somewhere, and update the sample workflow to use them so that it will run faster.
- [x] Update the docs to explain how to run the workflow for `process_training_data` and `train` and then swap in the pretrained car detection model and then run the rest of the workflow using that model. Then the predictions that come out of running the workflow should be good.

**Comment by cyberjoac** [comment]
Hi @lewfish, I find this issue very interesting, as I'm currently trying to get the Object Detection tutorial working.

My end goal would be to infer on new images.
Do you provide a pre-trained model on Potsdam or should I first run the training (12 hours on AWS Batch) and later on infer ? 

Thanks for any help that could prove very useful !

**Comment by lewfish** [comment]
> Do you provide a pre-trained model on Potsdam or should I first run the training (12 hours on AWS Batch) and later infer using the trained model ?

At the moment, you will have to train your own model, but I would like to complete this issue in the next few days. Then, you will be able to apply a pretrained car model to your own data without having to train one yourself.

**Comment by cyberjoac** [comment]
Sounds good, thanks much for the update 👍
