### ISSUE TITLE
Semantic Segmentation Labels not initializing properly from predictions when extent provided

### ISSUE THREAD

**Issue by chrisjkuch** [azavea/raster-vision#1995]
## 🐛 Bug

Creating a `SemanticSegmentationDiscreteLabels` object from predictions fails to properly populate labels when specifying an extent.

I may be calling this incorrectly, but here's what I'm trying to do:
* I have prediction chips that are numpy arrays with the predicted class as the value
* I have a `Box` that corresponds to the location of the chip within my raster in the pixel coordinate system of the raster
* Because I'm only interested in saving a portion of my labels, I specify an `extent` which is a `Box` in the pixel coordinate system of the raster that contains the area I want to save

I think the issue is [here](https://github.com/azavea/raster-vision/blob/82f05168338dd14a701050da3854ebfa8530406b/rastervision_core/rastervision/core/data/label/semantic_segmentation_labels.py#L289C4-L302C53). I'm a little confused about the indexing here - what's `src`, what's `dst`, and which arrays correspond to which coordinate system. The conversion `to_global_coords` and back `to_local_coords` seems to be where my mental model of what should happen differs from what's actually happening.

## To Reproduce

```python
import numpy as np
from rastervision.core.data.label import SemanticSegmentationDiscreteLabels
from rastervision.core.box import Box

# Imagine my raster is 100 x 100
# I have a prediction for the Box from (10,10) to (20,20)
window = Box(ymin=10, xmin=10, ymax=20, xmax=20)
prediction = np.ones((10, 10), dtype=np.uint8)

# I only want to save this portion of the labels so I specify it as my extent
extent = Box(ymin=10, xmin=10, ymax=20, xmax=20)

ssdl_test = SemanticSegmentationDiscreteLabels.from_predictions(
    windows=[window],
    predictions=[prediction],
    extent=extent,
    num_classes=2
)

ssdl_test.hit_mask.sum()
#> 0
ssdl_test.pixel_counts.sum()
#> 0
```

<sup>Created at 2023-11-17 18:26:40 CST by [reprexlite](https://github.com/jayqi/reprexlite) v0.5.0</sup>

## Expected behavior

I'd expect the hit mask and the pixel counts to sum to 100, since I should be loading 100 labelled predictions.

I think this is more along the lines of what I'd expect:

```python
def add_window(self, window: Box, pixel_class_ids: np.ndarray) -> None:
        # Calculate the intersection in case the window doesn't overlap 
        # with our specified extent
        window_dst = window.intersection(self.extent)
        
        # Convert to our local coordinate system
        window_src = window_dst.to_local_coords(self.extent)
        src_yslice, src_xslice = window_src.to_slices()

        pixel_class_ids = pixel_class_ids.astype(self.dtype)
        window_pixel_counts = self.pixel_counts[:, src_yslice, src_xslice]
        for ch_class_id, ch in enumerate(window_pixel_counts):
            ch[pixel_class_ids == ch_class_id] += 1
        self.hit_mask[src_yslice, src_xslice] = True
```

## Environment

Linux (Ubuntu), conda, python 3.10.12
rastervision==0.21.3
rastervision-aws-batch==0.21.3
rastervision-aws-s3==0.21.3
rastervision-core==0.21.3
rastervision-pipeline==0.21.3
rastervision-pytorch-backend==0.21.3
rastervision-pytorch-learner==0.21.3

**Comment by AdeelH** [comment]
`SemanticSegmentationLabels` does not provide a mechanism for subsetting the extent. If you want to do that, you will need something like the following:

```py
import numpy as np
from rastervision.core.data.label import SemanticSegmentationDiscreteLabels
from rastervision.core.box import Box

# Imagine my raster is 100 x 100
# I have a prediction for the Box from (10,10) to (20,20)
window = Box(ymin=10, xmin=10, ymax=20, xmax=20)
prediction = np.ones((10, 10), dtype=np.uint8)

# define bbox to spatially subset the full raster
bbox = Box(ymin=10, xmin=10, ymax=20, xmax=20)
# the RV convention is to use "extent" to mean a Box(0, 0, H, W) box
extent = bbox.extent

# the window coords as coords within the bbox
# i.e. Box(10, 10, 20, 20) --> Box(0, 0, 10, 10)
window_bbox_coords = window.to_local_coords(bbox)

ssdl_test = SemanticSegmentationDiscreteLabels.from_predictions(
    windows=[window_bbox_coords],
    predictions=[prediction],
    extent=extent,
    num_classes=2
)

ssdl_test.hit_mask.sum()
#> 100
ssdl_test.pixel_counts.sum()
#> 100
```

---
>I think the issue is [here](https://github.com/azavea/raster-vision/blob/82f05168338dd14a701050da3854ebfa8530406b/rastervision_core/rastervision/core/data/label/semantic_segmentation_labels.py#L289C4-L302C53). I'm a little confused about the indexing here - what's src, what's dst, and which arrays correspond to which coordinate system. The conversion to_global_coords and back to_local_coords seems to be where my mental model of what should happen differs from what's actually happening.

Yeah, that bit of code is not the clearest. 

Imagine `self.extent` is `Box(0, 0, 100, 100)` and `window` is `Box(80, 80, 120, 120)` and `pixel_class_ids` is a 40x40 array corresponding to the window. What we want to do is read from `pixel_class_ids[:20, :20]` write to `self.pixel_counts[:, 80:100, 80:100]`

So `window_dst` will be `Box(80, 80, 100, 100)` and `window_src` will be `Box(0, 0, 20, 20)` i.e. the coords within the `pixel_class_ids` array.

Here's the code with some more annotation (and some lines moved around):

```py
    def add_window(self, window: Box, pixel_class_ids: np.ndarray) -> None:
        # The window might overflow the extent, so we subset the window to
        # the portion that intersects with the extent.
        # dst := the self.pixel_counts array
        window_dst = window.intersection(self.extent)

        # Map subsetted window to the appropriate coords within the input
        # pixel_class_ids array.
        # src := the input pixel_class_ids array
        window_src = window_dst.to_global_coords(
            self.extent).to_local_coords(window)

        # read sub-window from the source array
        src_yslice, src_xslice = window_src.to_slices()
        pixel_class_ids = pixel_class_ids.astype(self.dtype)
        pixel_class_ids = pixel_class_ids[..., src_yslice, src_xslice]

        # write sub-window in the destination array
        dst_yslice, dst_xslice = window_dst.to_slices()
        window_pixel_counts = self.pixel_counts[:, dst_yslice, dst_xslice]
        for ch_class_id, ch in enumerate(window_pixel_counts):
            ch[pixel_class_ids == ch_class_id] += 1
        self.hit_mask[dst_yslice, dst_xslice] = True
```

**Comment by AdeelH** [comment]
Closing this now. Feel free to reopen if there are more questions.
