### ISSUE TITLE
Compute RasterStats from transformed RasterSource

### ISSUE THREAD

**Issue by bdevoghel** [azavea/raster-vision#2177]
## 🚀 Feature

When computing [RasterStats](https://docs.rastervision.io/en/stable/api_reference/_generated/rastervision.core.raster_stats.RasterStats.html) from a RasterSource (eg. in my case, to create a [StatsTransformer](https://docs.rastervision.io/en/stable/api_reference/_generated/rastervision.core.data.raster_transformer.stats_transformer.StatsTransformer.html)), the [chips are retrieved as raw chips](https://github.com/azavea/raster-vision/blob/b74e30e8d2f4d8835bcd930b309bf9b88c75e8cd/rastervision_core/rastervision/core/raster_stats.py#L256C26-L256C34).
It would be great to allow to get transformed chips too.

## Motivation

I'd like to obtain a StatsTransformer from a RasterSource which has `raster_transforms`, in order to normalize (with this StatsTransformer) the RasterSource.
Not allowing for this implies mathematical limitations, as normalization and transformation are not [commutative](https://en.wikipedia.org/wiki/Commutative_property).

## Pitch

[`raster_stats.get_chip()`](https://github.com/azavea/raster-vision/blob/b74e30e8d2f4d8835bcd930b309bf9b88c75e8cd/rastervision_core/rastervision/core/raster_stats.py#L252) should have an additional (optional) parameter to define if the chip to get is raw or not.

```python
def get_chip(raster_source: 'RasterSource',
             window: 'Box',
             nodata_value: Optional[float] = 0
             get_raw: Optional[bool] = True) -> Optional[np.ndarray]:
    """Return chip or None if all values are NODATA."""
    if get_raw:
        chip = raster_source.get_raw_chip(window).astype(float)
    else:
        chip = raster_source.get_chip(window).astype(float)
    ...
```
This option should be propagated in methods using `get_chip()` to allow for its use, this should be straightforward.

## Alternatives

No alternatives are available at the moment, as far as I know.

## Additional context

I would be available to implement a fix in a PR if this is validated.

**Comment by AdeelH** [comment]
Thanks for the comprehensive issue! This makes perfect sense to me. The only thing I'm debating is whether we should get rid of the raw chip sampling entirely and only have `RasterStats` sample transformed chips since that seems more intuitive to me. The tricky thing there would be ensuring `channel_order` is handled correctly in `StatsTransformer` and ensuring that we don't break backward compatibility.

Let me think about it some more and get back to you about a PR.

**Comment by AdeelH** [comment]
Hey! I ended up making `get_chip()` the default. The backward-compatibility considerations made this a little tricky so I decided to handle it myself. But thanks again for the issue and I hope you will continue to contribute more in the future!
