### ISSUE TITLE
Move to a Docker only, Vagrantless development environment

### ISSUE THREAD

**Issue by lossyrob** [azavea/raster-vision#222]
While adding a layer between the development environment and Docker has some advantages, for this project in particular it represents an unnecessary layer of complexity. We should move our development environment to a docker-only environment.

**Comment by dustymugs** [comment]
Please do ;-) I don't use the vagrant process but do my work directly on my host and test in a running docker container (`docker ... --mount type=bind,...`)

**Comment by lewfish** [comment]
This is done for everything except using Packer and Terraform. Making a new issue for that stuff.
