### ISSUE TITLE
Runtime error when max_windows not set for SemanticSegmentationRandomGeoDataset

### ISSUE THREAD

**Issue by keves1** [azavea/raster-vision#2222]
## 🐛 Bug

When `max_windows` is not specified when initializing a SemanticSegmentationRandomWindowGeoDataset, a runtime error occurs when iterating through the dataloader. This is due to the default value resulting in the max allowed reads being set to np.inf.

## To Reproduce

```python
from rastervision.core.data import ClassConfig
from rastervision.core.data.utils import make_ss_scene
from rastervision.pytorch_learner import SemanticSegmentationRandomWindowGeoDataset

from torch.utils.data import DataLoader

image_uri = 's3://spacenet-dataset/spacenet/SN7_buildings/train/L15-0331E-1257N_1327_3160_13/images/global_monthly_2018_01_mosaic_L15-0331E-1257N_1327_3160_13.tif'
label_uri = 's3://spacenet-dataset/spacenet/SN7_buildings/train/L15-0331E-1257N_1327_3160_13/labels/global_monthly_2018_01_mosaic_L15-0331E-1257N_1327_3160_13_Buildings.geojson'

class_config = ClassConfig(
    names=['background', 'building'],
    colors=['lightgray', 'darkred'],
    null_class='background')

scene = make_ss_scene(
    class_config=class_config,
    image_uri=image_uri,
    label_vector_uri=label_uri,
    label_vector_default_class_id=class_config.get_class_id('building'),
    image_raster_source_kw=dict(allow_streaming=True))

dataset = SemanticSegmentationRandomWindowGeoDataset(scene, out_size=224, size_lims=[220,224]) # max_windows not set

dataloader = DataLoader(dataset, batch_size=5, shuffle=True, num_workers=0)
x, y = next(iter(dataloader))
```
Error message:
{
```
	"name": "RuntimeError",
	"message": "Storage size calculation overflowed with sizes=[9223372036854775807]",
	"stack": "---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[3], line 25
     22 dataset = SemanticSegmentationRandomWindowGeoDataset(scene, out_size=224, size_lims=[220,224]) # max_windows not set
     24 dataloader = DataLoader(dataset, batch_size=5, shuffle=True, num_workers=0)
---> 25 x, y = next(iter(dataloader))

File /opt/conda/lib/python3.11/site-packages/torch/utils/data/dataloader.py:631, in _BaseDataLoaderIter.__next__(self)
    628 if self._sampler_iter is None:
    629     # TODO(https://github.com/pytorch/pytorch/issues/76750)
    630     self._reset()  # type: ignore[call-arg]
--> 631 data = self._next_data()
    632 self._num_yielded += 1
    633 if self._dataset_kind == _DatasetKind.Iterable and \\
    634         self._IterableDataset_len_called is not None and \\
    635         self._num_yielded > self._IterableDataset_len_called:

File /opt/conda/lib/python3.11/site-packages/torch/utils/data/dataloader.py:674, in _SingleProcessDataLoaderIter._next_data(self)
    673 def _next_data(self):
--> 674     index = self._next_index()  # may raise StopIteration
    675     data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
    676     if self._pin_memory:

File /opt/conda/lib/python3.11/site-packages/torch/utils/data/dataloader.py:621, in _BaseDataLoaderIter._next_index(self)
    620 def _next_index(self):
--> 621     return next(self._sampler_iter)

File /opt/conda/lib/python3.11/site-packages/torch/utils/data/sampler.py:287, in BatchSampler.__iter__(self)
    285 batch = [0] * self.batch_size
    286 idx_in_batch = 0
--> 287 for idx in self.sampler:
    288     batch[idx_in_batch] = idx
    289     idx_in_batch += 1

File /opt/conda/lib/python3.11/site-packages/torch/utils/data/sampler.py:167, in RandomSampler.__iter__(self)
    165 else:
    166     for _ in range(self.num_samples // n):
--> 167         yield from torch.randperm(n, generator=generator).tolist()
    168     yield from torch.randperm(n, generator=generator).tolist()[:self.num_samples % n]

RuntimeError: Storage size calculation overflowed with sizes=[9223372036854775807]"
```
}

## Expected behavior

I think that this should not cause an error if using default values. I think it would be better if max_windows was a required argument, or (maybe not as good of an option), provide an integer default value. I assume this change would be applied to the base class RandomWindowGeoDataset.

I'd be glad to create a PR for this if you agree with the change.

## Environment

Running Raster Vision directly in Windows is not supported, and we recommend that you run it from within a Docker container.

 - How you installed and are running Raster Vision (pip install on local vs. inside Docker image): Docker image
 - Raster Vision version or commit: 0.30.2-dev
 - OS (e.g., Linux): Ubuntu 22.04.3
 - Python version: 3.11.6
 - CUDA/cuDNN version if running on GPU: N/A
 - Any other relevant information:

**Comment by keves1** [comment]
Sounds good, I'll work on that. What's the best way to develop using the Docker image? I see there is a script to build the image, but when I import rastervision within the container it is using the files copied into the container rather than the files that are in my local filesystem, so do I need to rebuild the image every time I make changes?

**Comment by AdeelH** [comment]
If you use the `docker/run` script, it will [mount your local repo directory to `/opt/src`](https://github.com/azavea/raster-vision/blob/eb83d3081d9ffcfbe45f1e74be722ee67c380ec6/docker/run#L144), so your changes will be available inside the container in realtime--no need to rebuild.

For development, I use VS Code with the Python interpreter being a mamba environment that has Raster Vision installed in editable mode from source (`pip install -e rastervision_pipeline/`, `pip install -e rastervision_core/`, `pip install -e rastervision_pytorch_learner/` etc.). The environment also has yapf and flake8 installed (make sure to use the versions in `requirements-dev.txt`) so that the code is always compliant with `scripts/style_tests`.
