### ISSUE TITLE
Override backend config options

### ISSUE THREAD

**Issue by lewfish** [azavea/raster-vision#237]
Each backend is presumed to have its own config format for training. Currently, we handle this by referencing a backend config file from within the RV train command config and workflow config files. This can get annoying because every time you want to modify an existing workflow, you need to create a new backend config file, upload it, and reference the new file name from within the workflow config. I think it would be easier if we did away with backend config files and just inlined its contents as a string field in the RV config file. It's safe to assume that all backend config files will be strings, although we can't know in advance what the format will be. When training a model, the backend class will be responsible for writing this string to a file which will be fed into the actual backend executable. Or, if the actual backend executable takes command line args instead of a config file, the backend class can parse the config string into the appropriate command line args.

**Comment by lewfish** [comment]
Does anybody have any objections to this?

**Comment by lossyrob** [comment]
My worries are:
- It will explode out the workflow configs
- It is easier to reuse a backend config for a workflow config when it's a separate file

I think a flexible and perhaps over-engineered solution would be to have parts of a workflow config be able to reference an external JSON file (s3 or local to begin with), and RV could know to hydrate that section with the JSON object that exists in the external file. Also, we could have properties defined in the workflow config to take precedence over what's in the file, i.e. be able to overwrite some of the properties that the specific workflow would like to tweak.

I had proposed some of these properties as part of the WIP STAC spec a while back: https://github.com/radiantearth/stac-spec/blob/feature/add-flat-file-spec/spec/json/README.md#embedding-of-linked-elements - something similar to that could be useful here.

**Comment by lewfish** [comment]
I think that sounds like a good approach.

**Comment by lewfish** [comment]
Look at TypeSafe config
