### ISSUE TITLE
Avoid archiving chips from previous run

### ISSUE THREAD

**Issue by lewfish** [azavea/raster-vision#249]
If you make chips for classification and specify a local path for the output zip file, a local directory (adjacent to the zip file) is used to store the chips before zipping. If you had chips in that directory from a previous run, they will be included in the resulting zip file which is incorrect. We could handle this by storing the chips in a (freshly created) temp dir and make the zip based on that directory.  This problem also occurs for the directory of debug chips for object detection.

**Comment by lossyrob** [comment]
We also need to think through how we rerun/replace files  generally, e.g. training
