### ISSUE TITLE
Add support for AOI polygons

### ISSUE THREAD

**Issue by lewfish** [azavea/raster-vision#270]
Currently, it is necessary to exhaustively label scenes for object detection. It would be nice to just label parts of the scene (AOIs) and specify those AOIs as polygons in the label file. We could implement this by using a special `class_name` for the AOI polyons, and then specifying that class name as an option for `make_training_chips` using an optional `aoi_class_name` field.

**Comment by lewfish** [comment]
Instead of using a special class name to designate the AOI polygons, it might be simpler to just use a different file containing the AOI polygons. This file will be referenced in the make_training_chips options, and the code around https://github.com/azavea/raster-vision/blob/develop/src/rastervision/ml_tasks/object_detection.py#L92 will need to be modified to build a set of shapely polygons, which will be used to test if each window lies within that set of polygons. The Box class has a to_shapely method which should be useful.

**Comment by simonkassel** [comment]
are you thinking that it would look something like this in workflow config:

```        "ground_truth_label_store":
        {
            "object_detection_geojson_file":
            {
                "uri": "s3://raster-vision-spacenet/AOI_1_Rio/buildingLabels/Rio_Buildings_Public_AOI_v2.geojson",
                "aoi":"s3://raster-vision-spacenet/AOI_1_Rio/buildingLabels/Rio_OUTLINE_Public_AOI.geojson"
            }
        }
```

**Comment by lewfish** [comment]
I would name it `aoi_uri` and associated it with LabelStore, not ObjectDetectionGeoJSON file. Originally I was just thinking that this would work for object detection, but there's no reason we can't make it work for all the tasks just by moving the code to a higher level. If we filtered the `windows` right after this line, it will work for all tasks. https://github.com/azavea/raster-vision/blob/develop/src/rastervision/core/ml_task.py#L120

**Comment by simonkassel** [comment]
ok, that makes sense
