### ISSUE TITLE
Make sure all dependency versions are correct

### ISSUE THREAD

**Issue by tnation14** [azavea/raster-vision#276]
`develop` builds are currently failing because the pinned version of `git` (version `1:2.7.4-0ubuntu1.3`) isn't available on Ubuntu Xenial. Pin git to `1:2.7.4-0ubuntu1.4`, and make sure all other dependencies are pinned to available versions. In order to reduce the maintenance burden of keeping these pins up to date, it may be better to use wildcard notation and pin to a major release instead of a patch.

**Comment by lewfish** [comment]
Thanks for doing this. I didn't know what I was doing when I pinned it to those version :)

**Comment by tnation14** [comment]
Closed via #278
