### ISSUE TITLE
Use model trained by RV as fine-tuning checkpoint

### ISSUE THREAD

**Issue by lewfish** [azavea/raster-vision#286]
This will let us train a model on one dataset, and then use it as a starting point for training a model on a different dataset. It's immediately useful as a way of speeding up our integration tests. The idea is to train the model part of the way, store it, and use it as a starting point for the integration test which will bring it into the home stretch.

**Comment by lewfish** [comment]
After training a model, you just need to create a `.tar.gz` file with a directory containing the `model.ckpt*` files and `pipeline.config` (actually that's not strictly necessary, but is a good idea). You can then use that file just as you would use the `.tar.gz` files from the TFOD model zoo.
```
root@e790c4fc3579:/opt/src# ls /opt/data/lf-dev/rv-output/raw-datasets/tiny-test/datasets/object-detection/models/default/output/
checkpoint  eval  model  model.ckpt.data-00000-of-00001  model.ckpt.index  model.ckpt.meta  pipeline.config  train
root@e790c4fc3579:/opt/src# mkdir /opt/data/lf-dev/tiny-test/object-detection/ssd_mobilenet_v1_tiny_test
root@e790c4fc3579:/opt/src# cp /opt/data/lf-dev/rv-output/raw-datasets/tiny-test/datasets/object-detection/models/default/output/model.ckpt* \
    /opt/data/lf-dev/tiny-test/object-detection/ssd_mobilenet_v1_tiny_test/
root@e790c4fc3579:/opt/src# cp /opt/data/lf-dev/rv-output/raw-datasets/tiny-test/datasets/object-detection/models/default/output/pipeline.config \
    /opt/data/lf-dev/tiny-test/object-detection/ssd_mobilenet_v1_tiny_test/
root@e790c4fc3579:/opt/src# cd /opt/data/lf-dev/tiny-test/object-detection/
root@e790c4fc3579:/opt/data/lf-dev/tiny-test/object-detection# tar czf ssd_mobilenet_v1_tiny_test.tar.gz ssd_mobilenet_v1_tiny_test/
```

**Comment by lewfish** [comment]
The default behavior of TF OD API for fine-tuning models is to only copy over the base of the model (the Resnet50 or similar backbone) and *not* the object-detection specific parts of the model.  If you would like to copy over all variables, then you will need to insert `load_all_detection_checkpoint_vars: true` into the backend config file (beneath the `fine_tune_checkpoint` field). However, this also has the undesired effect of copying over the step number. This means that if you trained a model for 1000 steps, create the pretrained model zip file, and then use it in a new training job, the new training job will start training at step 1000.

**Comment by lewfish** [comment]
Similar to how we export the inference graph at the end of training, perhaps we should also generate the fine-tuning tar.gv package for convenience.

**Comment by lossyrob** [comment]
This issue should add bundling the `.tar.gz` file that contains the above format as part of the end of the `train` method on `TFObjectDetection`

Also document this as an FAQ answer
