### ISSUE TITLE
Fix ValueError Related to TFOD API and batch size

### ISSUE THREAD

**Issue by nholeman** [azavea/raster-vision#377]
While following the [Object Detection Tutorial](https://github.com/azavea/raster-vision/blob/develop/docs/object-detection.md#object-detection-tutorial), I encountered an error while [running a test workflow locally](https://github.com/azavea/raster-vision/blob/develop/docs/object-detection.md#running-a-test-workflow-locally).

The issue arises after the following steps:

1. Run `compute_raster_stats`, `make_training_chips`, and `train` on Potsdam data.
2. Replace the generated model with the trained car model.
3. Run `predict` and `eval`.

The error and relevant stack trace are below:

```
Traceback (most recent call last):
  ...
  File "/opt/src/rastervision/ml_backends/tf_object_detection_api.py", line 638, in predict
    self.session)
  File "/opt/src/rastervision/ml_backends/tf_object_detection_api.py", line 503, in compute_prediction
    [boxes, scores, class_ids], feed_dict={image_tensor: image_nps})
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1111, in _run
    str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (10, 300, 300, 3) for Tensor 'image_tensor:0', which has shape '(1, ?, ?, 3)'
```

It seems that, in this case, the TFOD api does not accept batch size 10. When the batch size is changed to 1, there is no error. Also, there is no error (regardless of batch size) when `predict` and `eval` are run on the model that is initially generated from training. This is strange because batch size 10 should be acceptable in both cases.

**Comment by lewfish** [comment]
Closed because we are discontinuing TF backends. Hi Nathan, if you're reading this!

**Comment by nholeman** [comment]
Hi Lewis! I'll allow it! haha
