### ISSUE TITLE
Implement `--dry-run` / `-n` option in CLI

### ISSUE THREAD

**Issue by lossyrob** [azavea/raster-vision#403]
We should have a `--dry-run`/`-n` option in the CLI which will print information about the commands to be run, but not actually run them. The CLI option exists, but needs to be implemented in the code.

**Comment by jamesmcclain** [comment]
In progress.

**Comment by lossyrob** [comment]
There are some incoming changes that should help this effort:

https://github.com/azavea/raster-vision/pull/413/files#diff-c9f912f218017f4453e836b4eee86210R66

Keeps track of skipped commands, so that they can be reported during a dry run. Commands are skipped either because they are the same as other experiment's commands, or because their output already exists.
