### ISSUE TITLE
Make sure training resumes for restarted jobs

### ISSUE THREAD

**Issue by lewfish** [azavea/raster-vision#422]
This may be a factor #106

**Comment by jamesmcclain** [comment]
As I understand it, the task is to verify that this is now the case.  Should it be true for the feature branch, or is there another branch that I should use?

**Comment by lossyrob** [comment]
This is now in the feature/api-refactor branch

**Comment by jamesmcclain** [comment]
> This is now in the feature/api-refactor branch

Okay, sounds good.

**Comment by jamesmcclain** [comment]
### Chip Classification ###

```
rastervision run aws_batch -e spacenet.chip_classification -a root_uri ${RVROOT}
```
then
```
rastervision run aws_batch -e spacenet.chip_classification -a root_uri ${RVROOT} --rerun train
```
![screenshot from 2018-10-08 13-20-39](https://user-images.githubusercontent.com/11281373/46634088-c4243f00-cb1d-11e8-8eba-71e333b20cb2.png)

**Comment by jamesmcclain** [comment]
### Object Detection ###

```
export ROOT_URI='s3://raster-vision-mcclain/xview'
export DATA_URI='s3://raster-vision-xview'
rastervision run aws_batch -e xview.object_detection -f *mobilenet* -a root_uri ${ROOT_URI} -a data_uri ${DATA_URI}
```

**Comment by jamesmcclain** [comment]
### Segmentation ###
