### ISSUE TITLE
Add ability for Predict command to split itself into groups of images

### ISSUE THREAD

**Issue by lossyrob** [azavea/raster-vision#428]
Right now, the Predict command will run a single command that predicts against all the validation and test scenes, sequentially. In the case where we are predicting against a large  set of images, we'll want to parallelize this work. In the AWS Batch instance, we'd want to issue several AWS batch commands with  subsets of the images to be predicted against. This would entail having a way for the predict configuration or command to turn a single command based on N images into a N/G command, each with roughly G images to predict against.

**Comment by lewfish** [comment]
I think this is subsumed by #551 now but not sure.
