### ISSUE TITLE
Figure out how to pip install on Windows

### ISSUE THREAD

**Issue by lewfish** [azavea/raster-vision#518]
We probably need to add some extra stuff to handle installing on Windows. Tyler @tgilcrest tried pip installing and got:

```
PS C:\Users\tgilcrest\repos> pip install rastervision
Collecting rastervision
  Using cached https://files.pythonhosted.org/packages/31/82/81b84ad2a93beaf0bde93eb8401f2144d4665f5a6c81d18ec9697e42df57/rastervision-0.8.0-py3-none-any.whl
Collecting pluginbase==0.7 (from rastervision)
  Using cached https://files.pythonhosted.org/packages/6e/f4/1db0a26c1c7fad81a1214ad1b02839a7bd98d8ba68f782f6edcc3d343441/pluginbase-0.7.tar.gz
Requirement already satisfied: scikit-learn==0.19.* in c:\programdata\anaconda3\lib\site-packages (from rastervision) (0.19.1)
Collecting rasterio==1.0.7 (from rastervision)
  Using cached https://files.pythonhosted.org/packages/ce/e3/86ef71d178887f2e365763607f974d5a70be9fbd422e4378bd8c16b8c306/rasterio-1.0.7.tar.gz
    Complete output from command python setup.py egg_info:
    INFO:root:Building on Windows requires extra options to setup.py to locate needed GDAL files. More information is available in the README.
    ERROR: A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\TGILCR~1\AppData\Local\Temp\pip-install-szdcethz\rasterio\
```

**Comment by lewfish** [comment]
A workaround found by @tgilcrest:

"I ended up not doing `pip install rastervision` because I was having too much trouble with the setup of rasterio and recognizing GDAL (I think that can be figured out, I just have been beating my head against it for a while.) What I did instead was install GDAL and Rasterio from here: https://www.lfd.uci.edu/~gohlke/pythonlibs/. Then, since that site only had `rasterio-1.0.8`, I cheated a little and changed `requirements.txt` to `rasterio==1.0.8` and then did `python setup.py install` for raster vision."

**Comment by liliangzhi110** [comment]
got it，thank you 😀

**Comment by jadecacho** [comment]
`(base) C:\Users\W-book\Anaconda3\pkgs>pip install rasterio-1.0.24+gdal24-cp35-cp35m-win_amd64.whl
ERROR: rasterio-1.0.24+gdal24-cp35-cp35m-win_amd64.whl is not a supported wheel on this platform.`

It's not letting me install the packages manually.

**Comment by sagar1899** [comment]
> We probably need to add some extra stuff to handle installing on Windows. Tyler @tgilcrest tried pip installing and got:
> 
> ```
> PS C:\Users\tgilcrest\repos> pip install rastervision
> Collecting rastervision
>   Using cached https://files.pythonhosted.org/packages/31/82/81b84ad2a93beaf0bde93eb8401f2144d4665f5a6c81d18ec9697e42df57/rastervision-0.8.0-py3-none-any.whl
> Collecting pluginbase==0.7 (from rastervision)
>   Using cached https://files.pythonhosted.org/packages/6e/f4/1db0a26c1c7fad81a1214ad1b02839a7bd98d8ba68f782f6edcc3d343441/pluginbase-0.7.tar.gz
> Requirement already satisfied: scikit-learn==0.19.* in c:\programdata\anaconda3\lib\site-packages (from rastervision) (0.19.1)
> Collecting rasterio==1.0.7 (from rastervision)
>   Using cached https://files.pythonhosted.org/packages/ce/e3/86ef71d178887f2e365763607f974d5a70be9fbd422e4378bd8c16b8c306/rasterio-1.0.7.tar.gz
>     Complete output from command python setup.py egg_info:
>     INFO:root:Building on Windows requires extra options to setup.py to locate needed GDAL files. More information is available in the README.
>     ERROR: A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.
> 
>     ----------------------------------------
> Command "python setup.py egg_info" failed with error code 1 in C:\Users\TGILCR~1\AppData\Local\Temp\pip-install-szdcethz\rasterio\
> ```

it need a path to gdal libraries and header files.
i installled raster vision 0.12 on python 3.6.2 on windows.

provide path in setup.cfg of rasterio package.
