### ISSUE TITLE
Allow plugins for commands

### ISSUE THREAD

**Issue by lossyrob** [azavea/raster-vision#540]
There are situations where we'd want to run other commands, such as post processing on ML output. This can be done by allowing for commands to be plugged in, which we currently do not do.

**Comment by lewfish** [comment]
This is related to #475 and should probably be done together.

**Comment by lewfish** [comment]
This can be handled in rv2 by overriding the existing `Pipeline` class and adding 1) a new method for the new command, and 2) the name of the command to the list of commands.
