### ISSUE TITLE
Single band raster labels

### ISSUE THREAD

**Issue by SFrav** [azavea/raster-vision#547]
How do we set a ClassMap for a single band raster? 
At the moment I am taking my single band label raster (with a value for each class) and then converting it into RGB.
Using the Potsdam semantic segmentation as a basis, is there a simple edit to the following:

`label_source = rv.LabelSourceConfig.builder(rv.SEMANTIC_SEGMENTATION_RASTER) \
        .with_rgb_class_map(task.class_map) \
        .with_raster_source(label_source_uri) \
        .build()`

Also, how do I make the output a single band raster? Is it simply changing `True` to `False`
`rv.LabelStoreConfig.builder(rv.SEMANTIC_SEGMENTATION_RASTER) \
        .with_rgb(True) \
        .build()`

I'm sure these are simple issues but I couldn't find it in the API.

**Comment by lossyrob** [comment]
@SFrav you don't have to use the `rgb_class_map`. The default is to not use an RGB class map, so you don't need to make the `with_rgb` call. There might have been a bug in 0.8.0 around this, so make sure you're using 0.8.1. In your case, you should be able to avoid making configuration calls that reference rgb class maps and it should work as expected.

Let me know if that works out for you, and thanks for creating the issue!

**Comment by SFrav** [comment]
Thanks for the quick reply!

Removing those calls in `0.8` and `latest` give the following error:

`  File "/opt/src/rastervision/data/label_source/semantic_segmentation_raster_source_config.py", line 125, in validate
    'You must set the rgb_class_map for '
rastervision.core.config.ConfigError: You must set the rgb_class_map for SemanticSegmentationRasterSourceConfig. Use "with_rgb_class_map".`

**Comment by lossyrob** [comment]
Sorry, needed to merge #541for it to work on 0.8, which I just did - after the travis build it should be published to the 0.8 docker container

**Comment by mlaradji** [comment]
I haven't tried the docker, but I don't think this change has been pushed to the PyPI releases yet; I've tried removing `.with_rgb_class_map(task.class_map)` on rastervision 0.8.1 and I get the same error as @SFrav :
```
rastervision.core.config.ConfigError: You must set the rgb_class_map for SemanticSegmentationRasterSourceConfig. Use "with_rgb_class_map".
```

Doing this on the `develop` branch of the `git` version works without error.

**Comment by lewfish** [comment]
This should be fixed in current and future version of RV.
