### ISSUE TITLE
Distributed execution of commands  

### ISSUE THREAD

**Issue by lossyrob** [azavea/raster-vision#551]
Develop architecture for executing commands in a distributed manner via Apache Spark.

For instance, the ANALYZE and CHIP commands can be executed in a distributed map-reduce job - the stats analyzer creates a single JSON file, while the CHIP command could create several large backend specific files.

TODO:

#### Initial refactor work

- [ ] Refactor `create_command` in `CommandConfig` to pass in configuration, not the entities. This will allow the command to decide how and when the entities (e.g. scenes) will be created, and so in the case of spark this can happen inside an executor instead of on the driver.
- [ ] Refactor backends to handle multiple chip files - right now we work with a `train.zip` and `test.zip` structure for chips, but the backends should handle a directory of files e.g. TFRecords - either in zip format or bare TFRecords -  so that Spark jobs can write multiple record files.

#### Implementation

- [ ] Create a Mixin for Commands, e.g. `SparkMixin`, that exposes a method that  takes a SparkContext  for use in creating RDDs and running the commands on Spark.
- [ ] Create a SparkExperimentRunner. This runner will only be able to process commands that have the appropriate Mixin. The Spark runner will assume that it is executing on the driver machine, and so will new up a SparkContext and pass that to the command.
- [ ] Implement Spark execution methods for the Analyze, Chip and Eval commands
- [ ] Decide whether or not Spark code should be tested in unit tests as well as implement integration tests that utilize the Spark runner
- [ ] Create a method for execution on EMR - this may mean some terraform in https://github.com/azavea/raster-vision-aws that spins up an EMR cluster, and submits `rastervision run` jobs that will execute the run command on the EMR master node for execution across the cluster.
- [ ] Test against SpaceNet semantic segmentation for building detection

**Comment by lossyrob** [comment]
Note on the "multiple runner" idea:

Decision point: Should we allow multiple runners, such that if the first runner is not available, the second runner is used? How could this be architected?

**Comment by lewfish** [comment]
Subsumed by #654
