### ISSUE TITLE
Ensure correct ROOT_URI is set.

### ISSUE THREAD

**Issue by nholeman** [azavea/raster-vision#552]
If Raster Vision is to be run on AWS Batch, the `ROOT_URI` needs to be a remote uri (e.g. `s3://...`). There should be a check to ensure this compatibility. Otherwise, errors happen downstream, and pinpointing the problem is not necessarily trivial.

**Comment by lewfish** [comment]
We are refactoring RV and in an attempt to make it simpler have removed file existence checks at the time when configs are being validated, so closing this.
