### ISSUE TITLE
Fix link to console script

### ISSUE THREAD

**Issue by lewfish** [azavea/raster-vision#553]
Fix docker/console link in https://docs.rastervision.io/en/0.8/setup.html#install-raster-vision

It should be https://github.com/azavea/raster-vision/blob/0.8/docker/console

Also look for similar broken links.

**Comment by jamesmcclain** [comment]
I used `wget --spider` to search for broken links.  I was not able to find any more except for ones of the following form:

![screenshot_2019-02-05_08-39-10](https://user-images.githubusercontent.com/11281373/52278170-66193400-2924-11e9-9af5-7803f44a3b23.png)

which appear to be auto-generated and do not seem to be visible on the page.
