### ISSUE TITLE
Improve docs

### ISSUE THREAD

**Issue by lewfish** [azavea/raster-vision#561]
This is a black box issue for estimation purposes. Smaller issues should be created that address specific things to improve.

**Comment by lossyrob** [comment]
Importing notes from documentation feedback sessions here. We can solve the quick ones and make issues for ones that seem more tricky as needed. This covers #516.

#### Intro

- [ ] Add images to top of documentation introduction that shows satellite, aerial, and oblique imagery. Can use predictions for object detection, semantic segmentation and chip classification as another visual queue.

#### Quickstart

- [ ] Make the Quickstart easier to find - should be towards the top of intro page and/or in sidebar.
- [ ] Put in visualizations of the data that is used by the tiny_spacenet example
- [ ] Document the use of a pre-trained model in the quickstart
- [ ] Explain that the model trained in the quickstart will perform very poorly and why
- [ ] Add QGIS visualization to quickstart - bad model output vs pretrained model output
- [ ] Include information about making predictions in the quickstart and link to the predictions page
- [ ] Add embedded map to quickstart
- [ ] Moving the prompt for docker run below the creating an ExperimentSet section - specific instructions for creating /opt/src/code directory and source code file before running anything.

#### QGIS Plugin

- [ ] Show image of QGIS environment setting
- [ ] QGIS link in the quick links of the docs page should be to the docs page, not the repo. The repository link can be up near the top of the QGIS docs in case that's what people want to navigate to.
- [ ] Mention that for QGIS plugin predict, path to predict package should be S3, HTTP, or local host file system, even if using docker

#### README

- [ ] README could include instructions on how to run (pip and quay)

#### General

- [ ] Ensure proper instructions for running Raster Vision on a local GPU machine. Related to #606

#### Broken Links

- [ ] https://docs.rastervision.io/en/0.8/setup.html#install-raster-vision -  docker/console link gives 404

**Comment by lossyrob** [comment]
Several issues were closed by #620; remaining feedback to be responded to have issues associated with them and the above checklist updated.
