### ISSUE TITLE
Validation accuracy

### ISSUE THREAD

**Issue by DaDaPi3** [azavea/raster-vision#60]
Validation accuracy in the score.json is different from it in the log.txt/stdout.txt.

BTW, the avg_accuracy in the validation_eval.py should be called overall_accuracy.

**Comment by DaDaPi3** [comment]
Seems the validation accuracy in the score.json file is the accuracy evaluated on the no_boundary ground truth, while the validation accuracy in the log.txt file is the accuracy evaluated on the full reference.

**Comment by lewfish** [comment]
This is true. Ideally the numbers would be the same, but I don't think this should cause any problems as long as your are aware that the numbers are computed differently. If you want to submit a PR for this, feel free.
