### ISSUE TITLE
Runner runs commands needlessly

### ISSUE THREAD

**Issue by lewfish** [azavea/raster-vision#608]
I ran a full workflow, then deleted the predict and eval output, then ran again (without `-r ...`) and it ran predict, eval, and then... train. Using the verbose flag, I saw that the train command expected three files which all exist, so I'm surprised it wanted to run it again.

**Comment by jamesmcclain** [comment]
> I ran a full workflow

Please be more explicit.

**Comment by lewfish** [comment]
> > I ran a full workflow
> 
> Please be more explicit.

I ran into it in the context of running a private project (I can provide details on Slack) but there's a good chance that you could replicate this with any experiment in the examples repo.

**Comment by lewfish** [comment]
I ran the `rastervision` command with the `--verbose` flag and got this output which may be helpful.

```
TRAIN from buildings_semantic_segmentation
  INPUTS:
    s3://raster-vision-lf-dev/rv-output/vegas-spacenet/chip/buildings_semantic_segmentation/train-0.record
    s3://raster-vision-lf-dev/rv-output/vegas-spacenet/chip/buildings_semantic_segmentation/validation-0.record
    http://download.tensorflow.org/models/deeplabv3_mnv2_pascal_train_aug_2018_01_29.tar.gz
  OUTPUTS:
    s3://raster-vision-lf-dev/rv-output/vegas-spacenet/train/buildings_semantic_segmentation/model
    buildings_semantic_segmentation
```
