### ISSUE TITLE
Ctrl-c does not kill child commands

### ISSUE THREAD

**Issue by lewfish** [azavea/raster-vision#609]
It's a little hard to replicate this, but sometimes when running commands with the local runner, hitting ctrl-c kills the process, but not the child commands which were created by shelling out. I'm pretty sure this is due to the changes we just made to the command runner. We need to do the same thing we do in the backends when shelling out to avoid this.

**Comment by jamesmcclain** [comment]
This kind of [job control](https://en.wikipedia.org/wiki/Job_control_(Unix)) related issue might not be the easiest to deal with in Python.  I'll see if I can find an idea.

**Comment by lewfish** [comment]
> We need to do the same thing we do in the backends when shelling out to avoid this.

This is what I was referring to https://github.com/azavea/raster-vision/blob/develop/rastervision/backend/tf_deeplab.py#L609-L611
