### ISSUE TITLE
Handle feature extraction across window boundaries

### ISSUE THREAD

**Issue by lewfish** [azavea/raster-vision#638]
To avoid having an entire label array in memory at once, we are switching to making a prediction for a window and then saving that prediction, for all windows. This presents a problem for feature extraction: if a feature lies across window boundaries, it will appear as two features. To fix this, we need to have a post-processing step that merges features that are suspected to be split. This is reminiscent of the post-processing step we do for object detection, where we face the same problem. 

I don't think this is a high-priority right now.

@jamesmcclain

**Comment by jamesmcclain** [comment]
Based on discussion, shouldn't this be closed (or moved to a lower-priority column)?

**Comment by lewfish** [comment]
Yes, I just moved it to backlog.

**Comment by lewfish** [comment]
This is obviated by the fact that in RV2 we are no longer making predictions in a streaming fashion and we assume that the prediction raster for an entire scene fits into RAM. This means there is a limit on the size of a scene.
