### ISSUE TITLE
Separate Vector Evaluation and unit test

### ISSUE THREAD

**Issue by jamesmcclain** [azavea/raster-vision#642]
![screenshot from 2018-12-29 21-02-42](https://user-images.githubusercontent.com/11281373/50543720-70217780-0bad-11e9-963a-b9b5127c562f.png)

**Comment by lewfish** [comment]
As part of this, we should add a unit test to check that the vector eval works correctly.

**Comment by lewfish** [comment]
With the current approach, I think the average eval item for vectors is getting merged into the one for rasters. Separating the vector eval into a separate file should fix this. But if we decide to stick with the current combined eval, we will need to fix this bug.
