### ISSUE TITLE
Optimize StatsAnalyzer/RasterStats logic

### ISSUE THREAD

**Issue by lossyrob** [azavea/raster-vision#648]
The StatsAnalyzer allows users to get statistics of their raster data that can then be used by the StatsTransformer to rescale the data from wider datatypes to uint8.

The StatsAnalyzer however is *very* slow. This issue is to optimize the logic.

The StatsAnalyzer uses the [RasterStats](https://github.com/azavea/raster-vision/blob/1b2543ac3ac261352bba07403dd57c106cac731b/rastervision/core/raster_stats.py)  to compute the statistics. There are a couple of bottlenecks here:
- The logic uses a chip stream to compute the means, and then the standard deviation - the std calculation recalculates the mean, so the chip collection is iterated over an additional time unnecessarily.
- The stats are computed over the entire dataset, when an approximation could take a sample of the data and perform adequately.

This issue should solve the performance issues with StatsAnalyzer to increase speed by addressing the above issues and potentially exploring other ways to optimize the logic.

**Comment by ljvmiranda921** [comment]
Hi @lossyrob and @lewfish , yes the `StatsAnalyzer` is very slow. I'm wondering if it's possible and safe to skip this step? What's the best way to do that? For reference, I'm following the Rastervision quickstart tutorial
