### ISSUE TITLE
"pip install rastervision" error on Ubuntu 18.04.1

### ISSUE THREAD

**Issue by ChristophPie** [azavea/raster-vision#655]
After lots of (unsuccessful) trying to install **rastervision** on Windows, I now decided to try on a fresh Ubuntu 18.04.1 to make that there is a well defined environment. I did the following steps:

1. Install Ubuntu, Update package
2. sudo apt install python-pip
(following https://docs.rastervision.io/en/0.8/setup.html#install-raster-vision):
3. pip install rastervision

> 
> Collecting rastervision
>   Downloading https://files.pythonhosted.org/packages/68/1e/2dfc42ca237167fe8481af2e972c4c2a446328fd37f325835d54a81280d7/rastervision-0.8.1.tar.gz (168kB)
>     100% |████████████████████████████████| 174kB 834kB/s 
>     Complete output from command python setup.py egg_info:
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/tmp/pip-build-ydykIR/rastervision/setup.py", line 16, in <module>
>         with io.open(op.join(here, 'requirements.txt'), encoding='utf-8') as f:
>     IOError: [Errno 2] No such file or directory: '/tmp/pip-build-ydykIR/rastervision/requirements.txt'
>     
>     ----------------------------------------
> Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ydykIR/rastervision/

So what to do in this case? Seems that the pip package is missing a requirements.txt?

So I know.. googling and trying many things would be something I could do.. by with my minor knowledge I think I would create an "not well" definded environment where nobody can track the progress.
So i would like to go exemplary through this one.

Another question: is there any pre-build linux VM (VirtualBox) perhaps? I'd like to use QGIS along rastervision (use predict packages).

**Comment by mlaradji** [comment]
I am facing a similar issue on a clean install of Ubuntu 18.04.1 in an LXC container. The output I get is:
```
Collecting rastervision
  Downloading https://files.pythonhosted.org/packages/68/1e/2dfc42ca237167fe8481af2e972c4c2a446328fd37f325835d54a81280d7/rastervision-0.8.1.tar.gz (168kB)
    100% |████████████████████████████████| 174kB 2.0MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-c6ytti/rastervision/setup.py", line 16, in <module>
        with io.open(op.join(here, 'requirements.txt'), encoding='utf-8') as f:
    IOError: [Errno 2] No such file or directory: '/tmp/pip-build-c6ytti/rastervision/requirements.txt'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-c6ytti/rastervision/
```

Installing rastervision works fine in my `conda` environments.

**Comment by yddcode** [comment]
Dude, how do you use pip to install, can you give a tutorial?

**Comment by Roopesh-Bharatwaj-K-R** [comment]
pip install rastervision==0.21 will not give any error
