### ISSUE TITLE
Possibility to break up experiment stages?

### ISSUE THREAD

**Issue by busycalibrating** [azavea/raster-vision#673]
This feels like a very naive and silly question, but I'm trying to break up some steps that raster vision executes. Specifically I am trying to chip and generate my dataset (including train/validation/test sets) independent of pumping this dataset through a DL model. It isn't immediately obvious how to do this to me. My current thought process is:

I played a bit with the quickstart script provided in the latest development docs. Both the dry and regular runs worked fine.  Looking at the output for the dry run:
```
$ rastervision run local -p local_tiny_spacenet.py -n
Ensuring input files exist
Checking for existing output

Commands to be run in this order:
ANALYZE from local-tiny-spacenet-experiment

CHIP from local-tiny-spacenet-experiment
  DEPENDS ON: ANALYZE from local-tiny-spacenet-experiment

TRAIN from local-tiny-spacenet-experiment
  DEPENDS ON: CHIP from local-tiny-spacenet-experiment

BUNDLE from local-tiny-spacenet-experiment
  DEPENDS ON: TRAIN from local-tiny-spacenet-experiment
  DEPENDS ON: ANALYZE from local-tiny-spacenet-experiment

PREDICT from local-tiny-spacenet-experiment
  DEPENDS ON: TRAIN from local-tiny-spacenet-experiment
  DEPENDS ON: ANALYZE from local-tiny-spacenet-experiment

EVAL from local-tiny-spacenet-experiment
  DEPENDS ON: PREDICT from local-tiny-spacenet-experiment
  DEPENDS ON: ANALYZE from local-tiny-spacenet-experiment


Shell commands to be issued:
  python -m rastervision  run_command <path-to>\raster-vision-quickstart\analyze\local-tiny-spacenet-experiment\command-config.json
  python -m rastervision  run_command <path-to>\raster-vision-quickstart\chip\local-tiny-spacenet-experiment\command-config.json
  python -m rastervision  run_command <path-to>\raster-vision-quickstart\train\local-tiny-spacenet-experiment\command-config.json
  python -m rastervision  run_command <path-to>\raster-vision-quickstart\bundle\local-tiny-spacenet-experiment\command-config.json
  python -m rastervision  run_command <path-to>\raster-vision-quickstart\predict\local-tiny-spacenet-experiment\command-config.json
  python -m rastervision  run_command <path-to>\raster-vision-quickstart\eval\local-tiny-spacenet-experiment\command-config.json
```
It's clear to me that these steps are segmented from each other so I assumed there should be a way to specify the experiment to only execute, say `analyze` and `chip` (I'm not totally sure where the dataset is created, I presume in the `chip` stage).

I've tried just running these shell commands with no luck, as well as removing various parts of the ExperimentSet, which also gives me errors. Any suggestions?

**Comment by lossyrob** [comment]
@busycalibrating thanks for checking RV out, and raising the issue!

The way to execute individual commands  is to list them after the options, e.g.

```
$ rastervision run local -p local_tiny_spacenet.py -n chip
```

or 

```
$ rastervision run local -p local_tiny_spacenet.py -n analyze chip train
```

The CLI help will hopefully give some guidance to options:

```
$ rastervision --help
$ rastervision run --help
```

**Comment by busycalibrating** [comment]
Thanks for the reply! Awesome, that works. What I'd really like to be able to do is to be to separate the dataset generation part from the model training and able to generate a dataset without having to specify a backend, and then be able to pass along that dataset to another experiment without having to have the same ExperimentConfig (along the lines of `.with_dataset(import(dataset))`). Is this possible, or these stages more codependent than I thought?
