### ISSUE TITLE
Read from raster without downloading

### ISSUE THREAD

**Issue by lewfish** [azavea/raster-vision#691]
In the constructor of the `RasterioRasterSource` a bunch of metadata (and a small window) is extracted from the corresponding image. Currently we are downloading the whole file (and then deleting it to save disk space) which is inefficient. Ideally we could use Rasterio's ability to read directly from S3 URIs, but after implementing this, I found that there were some issues that I could not resolve. 

Since downloading from S3 to EC2 is fast, this might not be a big bottleneck, but if it is, we should dig deeper into these issues and try to get it to work. In case we want to resurrect this work, the branch that enables this is https://github.com/azavea/raster-vision/tree/lf/save-space

* When building a VRT using an S3 URI for a Spacenet image, it takes 18 seconds which seems much longer than it should take. 
```
time gdalbuildvrt /opt/data/test.vrt /vsis3/spacenet-dataset/SpaceNet_Buildings_Dataset_Round2/spacenetV2_Train/AOI_2_Vegas/RGB-PanSharpen/RGB-PanSharpen_AOI_2_Vegas_img1332.tif
0...10...20...30...40...50...60...70...80...90...100 - done.

real	0m18.100s
user	0m0.100s
sys	0m0.080s
```
This is especially strange considering that downloading the image only takes 1s as seen below.
```
time aws s3 cp s3://spacenet-dataset/SpaceNet_Buildings_Dataset_Round2/spacenetV2_Train/AOI_2_Vegas/RGB-PanSharpen/RGB-PanSharpen_AOI_2_Vegas_img1332.tif /opt/data/chip.tif
download: s3://spacenet-dataset/SpaceNet_Buildings_Dataset_Round2/spacenetV2_Train/AOI_2_Vegas/RGB-PanSharpen/RGB-PanSharpen_AOI_2_Vegas_img1332.tif to ../data/chip.tif

real	0m0.966s
user	0m0.380s
sys	0m0.070s
```
* Doing a windowed read with a VRT built using S3 URIs works with Spacenet images. However, with a Potsdam image it doesn't work. First I build the VRT.
```
gdalbuildvrt /opt/data/test.vrt /vsis3/raster-vision-raw-data/isprs-potsdam/4_Ortho_RGBIR/top_potsdam_2_11_RGBIR.tif /vsis3/raster-vision-raw-data/isprs-potsdam/4_Ortho_RGBIR/top_potsdam_2_12_RGBIR.tif
0...10...20...30...40...50...60...70...80...90...100 - done.
```
Then, in Python I try to do a windowed read which fails.
```
>>> import rasterio
>>> d = rasterio.open('/opt/data/test.vrt')
>>> o = d.read(window=((0, 1), (0, 1)), boundless=False)
ERROR 4: `/vsis3/raster-vision-raw-data/isprs-potsdam/4_Ortho_RGBIR/top_potsdam_2_11_RGBIR.tif' not recognized as a supported file format.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "rasterio/_io.pyx", line 340, in rasterio._io.DatasetReaderBase.read
  File "rasterio/_io.pyx", line 655, in rasterio._io.DatasetReaderBase._read
OSError: Read or write failed
```

**Comment by AdeelH** [comment]
This might be possible now using the streaming functionality added by #1020
