### ISSUE TITLE
Take pass through docs before 0.9

### ISSUE THREAD

**Issue by lewfish** [azavea/raster-vision#716]
Fix low-hanging fruit and make issues for docs to add in the next release. 
* AOIs 
* NODATA
* Scalability

**Comment by busycalibrating** [comment]
One nice thing for future releases if you substantially change certain backend functionality is documenting how to setup raster vision locally without the use of your provided docker container. 

For example, when I was trying to first install it, I had to install the TF models for tf.object_detection and tf.deeplab. In the case of deeplab, you added a custom dataset entries to `models/research/deeplab/datasets/segmentation_dataset.py`, which I only found out when I dug through the docker container. As of 20 days ago, this script is deprecated in favour of `data_generator.py`. I'm still using the older version of deeplab so I haven't tested whether the same changes will resolve the issues I had initially, but this is just an example.
