### ISSUE TITLE
Avoid making training chips on NODATA chips for semseg

### ISSUE THREAD

**Issue by yoninachmany** [azavea/raster-vision#718]
Like https://github.com/azavea/raster-vision/pull/364, check chip before including its resulting data.

**Comment by lewfish** [comment]
We do this for object detection [here](https://github.com/azavea/raster-vision/blob/develop/rastervision/task/object_detection.py#L75-L76) and chip classification [here](https://github.com/azavea/raster-vision/blob/develop/rastervision/task/chip_classification.py#L42-L43). It appears that we are not implementing this for semantic segmentation. 

As a workaround, you could add an AOI to the scene that avoids the NODATA areas.

**Comment by AdeelH** [comment]
#1025
