### ISSUE TITLE
Improve integration tests

### ISSUE THREAD

**Issue by lewfish** [azavea/raster-vision#722]
We should make the tests run faster and more deterministically. I think we can do this by only running the train command for one step to check that it doesn't crash, which is how the semseg test already works. This will make things faster and more deterministic, but it doesn't check that the chips were produced correctly. So we should check that the chips are correct, but to make that deterministic, we need to seed any randomness in the chip generation process. 

Another issue is that the integration tests don't check whether things work when running remotely. I'm hoping we can do this using a mock S3 bucket the same we do for unit tests.

Another is to use AOIs (see #675)

**Comment by AdeelH** [comment]
Re: determinism
Suggestion: we can save the initial weights of a model that produces the right output and initialize the test model with those weights. Also, do the things suggested here: https://pytorch.org/docs/stable/notes/randomness.html
