### ISSUE TITLE
Create a Packer configuration that creates a GPU workload AMI

### ISSUE THREAD

**Issue by hectcastro** [azavea/raster-vision#74]
Capture the steps in https://docs.aws.amazon.com/batch/latest/userguide/batch-gpu-ami.html and https://github.com/azavea/raster-vision/issues/64#issuecomment-314477173 within a Packer configuration template. Also, try Googling around to make sure that no one has done the first part already.

**Comment by lewfish** [comment]
The AMI needs to have a 128GB root volume and 22 GB data volume.

**Comment by lewfish** [comment]
Also, use NVidia drivers 375.51
