### ISSUE TITLE
Test before release

### ISSUE THREAD

**Issue by lewfish** [azavea/raster-vision#757]
- [x] Test Quickstart
- [x] Read Examples readme
- [x] Test Examples repo setup
- [x] Test different options to `docker/run`
- [x] Run Rio chip classification example plus another example locally
- [x] Run one example remotely
- [ ] Install QGIS plugin and test it (not ready yet)

**Comment by lewfish** [comment]
Note: the docs are not getting published for some reason, so for now you will need to run `docker/run --docs` in this repo to view the docs at `localhost:8000`.

**Comment by simonkassel** [comment]
Everything looks good. I ran the rio chip classification and vegas object detection test experiments locally. I also did a test run of the rio chip classification remotely and kicked off a run of the full rio chip classification experiment to run remotely.
