### ISSUE TITLE
Correctly open rasters with ColorInterp=Palette 

### ISSUE THREAD

**Issue by AmitMY** [azavea/raster-vision#770]
Using docker `cpu-c2e3fea` which is latest as of this moment,

I'm trying to run rastervision on tiles, which are often PNG images, such as:

![image](https://user-images.githubusercontent.com/5757359/56205889-aea34b00-6053-11e9-9e2c-c99b6a9f2080.png)

> rastervision_1  | Executing rastervision predict /app/packages/COWC_Potsdam.zip /images/781033043.png output/COWC_Potsdam_781033043.png.json

Error:
>rastervision_1  | (node:6) UnhandledPromiseRejectionWarning: Error: Command failed: rastervision predict /app/packages/COWC_Potsdam.zip /images/781033043.png output/COWC_Potsdam_781033043.png.json
rastervision_1  | 2019-04-16 11:40:32.288841: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
rastervision_1  | /usr/local/lib/python3.5/dist-packages/pluginbase.py:439: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
rastervision_1  |   fromlist, level)
rastervision_1  | Traceback (most recent call last):
rastervision_1  |   File "rasterio/_base.pyx", line 199, in rasterio._base.DatasetBase.__init__
rastervision_1  |   File "rasterio/_shim.pyx", line 64, in rasterio._shim.open_dataset
rastervision_1  |   File "rasterio/_err.pyx", line 188, in rasterio._err.exc_wrap_pointer
rastervision_1  | *rasterio._err.CPLE_OpenFailedError: '/images/781033043.png' not recognized as a supported file format.*
rastervision_1  | 
rastervision_1  | During handling of the above exception, another exception occurred:
rastervision_1  | 
rastervision_1  | Traceback (most recent call last):
rastervision_1  |   File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
rastervision_1  |     "__main__", mod_spec)
rastervision_1  |   File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
rastervision_1  |     exec(code, run_globals)
rastervision_1  |   File "/opt/src/rastervision/__main__.py", line 17, in <module>
rastervision_1  |     rv.main()
rastervision_1  |   File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 722, in __call__
rastervision_1  |     return self.main(*args, **kwargs)
rastervision_1  |   File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 697, in main
rastervision_1  |     rv = self.invoke(ctx)
rastervision_1  |   File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1066, in invoke
rastervision_1  |     return _process_result(sub_ctx.command.invoke(sub_ctx))
rastervision_1  |   File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 895, in invoke
rastervision_1  |     return ctx.invoke(self.callback, **ctx.params)
rastervision_1  |   File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
rastervision_1  |     return callback(*args, **kwargs)
rastervision_1  |   File "/opt/src/rastervision/cli/main.py", line 279, in predict
rastervision_1  |     predictor.predict(image_uri, output_uri, export_config)
rastervision_1  |   File "/opt/src/rastervision/predictor.py", line 136, in predict
rastervision_1  |     scene = scene_config.create_scene(self.task_config, self.tmp_dir)
rastervision_1  |   File "/opt/src/rastervision/data/scene_config.py", line 35, in create_scene
rastervision_1  |     raster_source = self.raster_source.create_source(tmp_dir)
rastervision_1  |   File "/opt/src/rastervision/data/raster_source/rasterio_source_config.py", line 70, in create_source
rastervision_1  |     y_shift_meters=y_shift_meters)
rastervision_1  |   File "/opt/src/rastervision/data/raster_source/rasterio_source.py", line 98, in __init__
rastervision_1  |     with self.activate():
rastervision_1  |   File "/opt/src/rastervision/data/activate_mixin.py", line 21, in __enter__
rastervision_1  |     self.activate()
rastervision_1  |   File "/opt/src/rastervision/data/activate_mixin.py", line 54, in do_activate
rastervision_1  |     self._activate()
rastervision_1  |   File "/opt/src/rastervision/data/raster_source/rasterio_source.py", line 162, in _activate
rastervision_1  |     self.image_dataset = rasterio.open(self.imagery_path)
rastervision_1  |   File "/usr/local/lib/python3.5/dist-packages/rasterio/env.py", line 402, in wrapper
rastervision_1  |     return f(*args, **kwds)
rastervision_1  |   File "/usr/local/lib/python3.5/dist-packages/rasterio/__init__.py", line 217, in open
rastervision_1  |     s = DatasetReader(path, driver=driver, **kwargs)
rastervision_1  |   File "rasterio/_base.pyx", line 201, in rasterio._base.DatasetBase.__init__
rastervision_1  | rasterio.errors.RasterioIOError: '/images/781033043.png' not recognized as a supported file format.
rastervision_1  | Traceback (most recent call last):
rastervision_1  |   File "/usr/lib/python3.5/weakref.py", line 595, in _exitfunc
rastervision_1  |     f()
rastervision_1  |   File "/usr/lib/python3.5/weakref.py", line 519, in __call__
rastervision_1  |     return info.func(*info.args, **(info.kwargs or {}))
rastervision_1  |   File "/usr/lib/python3.5/tempfile.py", line 936, in _cleanup
rastervision_1  |     _rmtree(name)
rastervision_1  |   File "/usr/lib/python3.5/shutil.py", line 465, in rmtree
rastervision_1  |     onerror(os.lstat, path, sys.exc_info())
rastervision_1  |   File "/usr/lib/python3.5/shutil.py", line 463, in rmtree
rastervision_1  |     orig_st = os.lstat(path)
rastervision_1  | FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpg3688m6j/tmpjgh1b8hx/tmpt_pe9juz'
rastervision_1  | 
rastervision_1  |     at ChildProcess.exithandler (child_process.js:294:12)
rastervision_1  |     at ChildProcess.emit (events.js:189:13)
rastervision_1  |     at maybeClose (internal/child_process.js:970:16)
rastervision_1  |     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
rastervision_1  | (node:6) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
rastervision_1  | (node:6) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by lewfish** [comment]
I just tried this using that Docker image, predict package, and PNG file, and it was successful. I'm not sure why it didn't work for you. I was using this predict package: `https://s3.amazonaws.com/azavea-research-public-data/raster-vision/examples/model-zoo/cowc-od/predict_package.zip`

**Comment by AmitMY** [comment]
Same prediction package... Odd...

```bash
wget -O app/packages/COWC_Potsdam.zip https://s3.amazonaws.com/azavea-research-public-data/raster-vision/examples/model-zoo/cowc-od/predict_package.zip

wget -O /images/781033043.png https://user-images.githubusercontent.com/5757359/56205889-aea34b00-6053-11e9-9e2c-c99b6a9f2080.png

rastervision predict /app/packages/COWC_Potsdam.zip /images/781033043.png out.json
```

**Comment by AmitMY** [comment]
My bad! When I uploaded the file to GitHub, it changed :(

Here is the original image:
https://drive.google.com/file/d/13_kZVgidQ0o-GJSiGpeJAlKJ_lrXYupl/view?usp=sharing


So running the above bash code works, but using this image instead doesn't.

**Comment by lewfish** [comment]
I get a different error when I run it with that image. It's because that file has a single band and uses a color table, but the `channel_order` is `[0, 1, 2]`. I've never seen a file like that, but I would have assumed that GDAL/Rasterio would convert it to 3 bands. I'll look into a solution.

```
root@c9ab515303bb:/opt/src# rastervision predict /opt/data/model-zoo/cowc-od/predict_package.zip     /opt/data/temp/amit.png     /opt/data/temp/amit.json
/usr/local/lib/python3.5/dist-packages/pluginbase.py:439: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  fromlist, level)
2019-04-29 15:10:10.305335: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
/usr/local/lib/python3.5/dist-packages/rasterio/__init__.py:217: NotGeoreferencedWarning: Dataset has no geotransform set. The identity matrix may be returned.
  s = DatasetReader(path, driver=driver, **kwargs)
Traceback (most recent call last):
  File "/opt/src/rastervision/predictor.py", line 136, in predict
    scene = scene_config.create_scene(self.task_config, self.tmp_dir)
  File "/opt/src/rastervision/data/scene_config.py", line 35, in create_scene
    raster_source = self.raster_source.create_source(tmp_dir)
  File "/opt/src/rastervision/data/raster_source/rasterio_source_config.py", line 70, in create_source
    y_shift_meters=y_shift_meters)
  File "/opt/src/rastervision/data/raster_source/rasterio_source.py", line 109, in __init__
    self.validate_channel_order(channel_order, num_channels)
  File "/opt/src/rastervision/data/raster_source/raster_source.py", line 37, in validate_channel_order
    raise ChannelOrderError(channel_order, num_channels)
rastervision.data.raster_source.raster_source.ChannelOrderError: The channel_order=[0, 1, 2] contains a channel index >= num_channels=1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/src/rastervision/__main__.py", line 17, in <module>
    rv.main()
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/opt/src/rastervision/cli/main.py", line 279, in predict
    predictor.predict(image_uri, output_uri, export_config)
  File "/opt/src/rastervision/predictor.py", line 148, in predict
    'The predict package is using a channel_order '
ValueError: The predict package is using a channel_order with channels unavailable in the imagery.
To set a new channel_order that only uses channels available in the imagery, use the --channel-order option.
```

```
root@c9ab515303bb:/opt/src# gdalinfo /opt/data/temp/amit.png
Driver: PNG/Portable Network Graphics
Files: /opt/data/temp/amit.png
Size is 256, 256
Coordinate System is `'
Corner Coordinates:
Upper Left  (    0.0,    0.0)
Lower Left  (    0.0,  256.0)
Upper Right (  256.0,    0.0)
Lower Right (  256.0,  256.0)
Center      (  128.0,  128.0)
Band 1 Block=256x1 Type=Byte, ColorInterp=Palette
  NoData Value=0
  Color Table (RGB with 256 entries)
    0: 0,0,0,0
    1: 51,51,51,5
    2: 51,102,51,5
    3: 80,85,81,19
    4: 80,89,84,39
    5: 88,100,92,36
    6: 90,104,100,37
```

**Comment by lewfish** [comment]
I don't see a quick fix, so the workaround for now is to just convert the PNGs to standard ones that use 3 bands.
