### ISSUE TITLE
Not 2 GPU training problems

### ISSUE THREAD

**Issue by anlianglu** [azavea/raster-vision#771]
I have two GPU server, but the training time but I can only use one, what should I do to set him support two parallel training
![image](https://user-images.githubusercontent.com/12770958/56651218-29571080-66bb-11e9-94f2-fae64f60ccc0.png)
![image](https://user-images.githubusercontent.com/12770958/56651344-68856180-66bb-11e9-91f6-b3923af8bf40.png)

**Comment by jamesmcclain** [comment]
There is some variability in terms of how this is handled by the various backends.  In the case of DeepLab, for example, you must set `num_clones` to `2` (see [here](https://github.com/azavea/raster-vision/issues/252)).

**Comment by pacelu** [comment]
> There is some variability in terms of how this is handled by the various backends. In the case of DeepLab, for example, you must set `num_clones` to `2` (see [here](https://github.com/azavea/raster-vision/issues/252) and [here](https://github.com/azavea/raster-vision/pull/590)).

3Q
