### ISSUE TITLE
Many GPU speed problemMany GPU speed problem

### ISSUE THREAD

**Issue by pacelu** [azavea/raster-vision#777]
There is some variability in terms of how this is handled by the various backends.  In the case of DeepLab, for example, you must set `num_clones` to `2` (see [here](https://github.com/azavea/raster-vision/issues/252) and [here](https://github.com/azavea/raster-vision/pull/590)).

_Originally posted by @jamesmcclain in https://github.com/azavea/raster-vision/issues/771#issuecomment-486277149_ 

I have a two GPU server, I according to your tip modified the code, and successfully run up, but his training speed make me feel sick, my single GPU training speed is every 10 steps is 5 seconds, but double the GPU is ten step 18 seconds, I don't know what did I do wrong, today I put the double GPU tear down one of them, instead, faster speed, and speed of single GPU,ten step 5 seconds

**Comment by lewfish** [comment]
It sounds like you tried to use two GPUs and it slowed down instead of speeding up. We haven't used the `num_clones` option, and since this option is a part of Deeplab, I would search for help in that repo.

**Comment by pacelu** [comment]
> It sounds like you tried to use two GPUs and it slowed down instead of speeding up. We haven't used the `num_clones` option, and since this option is a part of Deeplab, I would search for help in that repo.
First , thank you!!!!!
Yes, I am one of the servers is 2 gpu， i used the num_clones option，Instead of three times slower，
![image](https://user-images.githubusercontent.com/12770958/57344845-60c5c280-717b-11e9-87ff-afad59b36464.png)
Because now 1 gpu training will cost me more than 24 hours, I am seeking to accelerate training method, so I bought 2 gpu server, but the result is not too easy,
![image](https://user-images.githubusercontent.com/12770958/57344962-d2057580-717b-11e9-955a-05ec2f679603.png)

Now I was watching tensorflow official GPUs demo,

![image](https://user-images.githubusercontent.com/12770958/57345188-7a1b3e80-717c-11e9-82f8-39d640594f4a.png)

Looking forward to your good news

**Comment by lewfish** [comment]
We are discontinuing the TF Deeplab backend, and this seems specific to that backend, so I'm closing this.
