### ISSUE TITLE
prediction acceleration 

### ISSUE THREAD

**Issue by asoxien** [azavea/raster-vision#802]
I have a server (with NVIDIA GEFORCE 1070ti with i7 2d generation) which allows me to make a prediction on a single satellite image of 0.5m GSD and 20km of swath in 7H. I would like to improve these results to make the prediction in 15min instead of 7H. What Server/GPU you advise me to use. I would like to stay on a rack server. thanks

**Comment by lewfish** [comment]
I think this is covered by https://github.com/azavea/raster-vision/issues/243 so I'm closing this issue.
