### ISSUE TITLE
Adjusting Path and Variables for Setup in Microsoft Windows

### ISSUE THREAD

**Issue by hugonbgg** [azavea/raster-vision#804]
After racking my brains I was able to install rastervision on Windows10.
I have questions on how to set environment variables to be compatible with Windows. In which file or in what way do I set the path?
Thanks!

Running the demo:

(raster_vision) C:\Users\Hugo\raster_vision>rastervision run local -p tiny_spacenet.py -n
Ensuring input files exist    [####################################]  100%
Checking for existing output  [####################################]  100%

Commands skipped because output already exists:
CHIP-0 from tiny-spacenet-experiment

Commands to be run in this order:
TRAIN-0 from tiny-spacenet-experiment

ANALYZE-0 from tiny-spacenet-experiment

BUNDLE-0 from tiny-spacenet-experiment
  DEPENDS ON: TRAIN-0 from tiny-spacenet-experiment
  DEPENDS ON: ANALYZE-0 from tiny-spacenet-experiment

PREDICT-0 from tiny-spacenet-experiment
  DEPENDS ON: TRAIN-0 from tiny-spacenet-experiment
  DEPENDS ON: ANALYZE-0 from tiny-spacenet-experiment

EVAL-0 from tiny-spacenet-experiment
  DEPENDS ON: ANALYZE-0 from tiny-spacenet-experiment
  DEPENDS ON: PREDICT-0 from tiny-spacenet-experiment

Shell commands to be issued:
  python -m rastervision  run_command /opt/data/rv\train\tiny-spacenet-experiment\command-config.json
  python -m rastervision  run_command /opt/data/rv\analyze\tiny-spacenet-experiment\command-config.json
  python -m rastervision  run_command /opt/data/rv\bundle\tiny-spacenet-experiment\command-config.json
  python -m rastervision  run_command /opt/data/rv\predict\tiny-spacenet-experiment\command-config.json
  python -m rastervision  run_command /opt/data/rv\eval\tiny-spacenet-experiment\command-config.json

(raster_vision) C:\Users\Hugo\raster_vision>

**Comment by lewfish** [comment]
Which environment variables are you trying to set? I would just follow whatever advice is on the web about setting Windows environment variables. It's been some time since I used Windows and don't know how to do that offhand.
