### ISSUE TITLE
What is the unit of .with_cell_size()?

### ISSUE THREAD

**Issue by lmbak** [azavea/raster-vision#807]
The documentation https://docs.rastervision.io/en/0.9/api.html#id1 states that in
 `rv.LabelSourceConfig.builder(rv.CHIP_CLASSIFICATION).with_cell_size(cell_size)` the `cell_size` is used to set the cell size of the chips. I am assuming that this is a unit in pixels? E.g. if i set this value to `10` the chips will be 10 by 10 pixels? Perhaps this clarification could be added to the documentation?

**Comment by lewfish** [comment]
Yes, it's in pixel units. I agree that would be a good clarification. Same goes for `chip_size`.

**Comment by lmbak** [comment]
Great. Thanks for the clarification.
