### ISSUE TITLE
Fine Tuning ...

### ISSUE THREAD

**Issue by VanitarNordic** [azavea/raster-vision#81]
Hello,

Can you guide me how can I fine tune the model for a different dataset and naturally different number of classes?

I suppose to create the dataset in your format I think, at the beginning.

**Comment by lewfish** [comment]
I would just look at how we are doing things for the Potsdam dataset on semseg and the Planet Kaggle datasets for tagging, and think about how things would need to change for your dataset. At the very least, you will need to write a new data generator and modify the dataset factory to handle the new dataset.
