### ISSUE TITLE
pre-trained weights

### ISSUE THREAD

**Issue by sanjeev-** [azavea/raster-vision#82]
Hi -- 

I am looking to do semantic segmentation (no need for tagging, detection, or object recognition at this stage) and I was wondering if anyone has the pre-trained weights available for download?  It can be on any of the models, just want to test it out for now.

Thanks vm

**Comment by lewfish** [comment]
We are starting to provide model weights for our running example car detection dataset. See https://github.com/azavea/raster-vision/blob/develop/docs/object-detection.md and https://github.com/azavea/raster-vision-data/releases
