### ISSUE TITLE
Oversampling of rare classes

### ISSUE THREAD

**Issue by lmbak** [azavea/raster-vision#853]
Since the removal of Fastai backends there is no more option for oversampling (right? Or did I miss anything?). Would this be a usefull feature? In my case I would use it for the chip classification, where implementation might be easier than for semseg and object detection.

Would the correct construction be to provide the [DataLoader](https://github.com/azavea/raster-vision/blob/master/rastervision/backend/torch_utils/chip_classification/data.py#L24-L35) classes with a [Sampler ](https://pytorch.org/docs/stable/data.html#data-loading-order-and-sampler) object? More specifically the [WeightedRandomSampler](https://pytorch.org/docs/stable/data.html#torch.utils.data.WeightedRandomSampler)? The weights list for this sampler can then be calculated/constructed [somewhere in the DatasetFolder](https://github.com/azavea/raster-vision/blob/master/rastervision/backend/torch_utils/chip_classification/folder.py#L100-L116)?

@lewfish Could you let me know if we need this and if the described way is technically correct/how you would do it?

**Comment by lmbak** [comment]
Perhaps slightly easier to build is a class equalizer, as this will most likely cover most use cases (mine at least). This would result in a 0.5:0.5 probability for 2 classes, or 0.33:0.33:0.33 for 3 etc.

**Comment by lewfish** [comment]
Right, there's no oversampling option. But you should be able to add it back. I don't need it, but if you think it will be useful, I would encourage you to add it. The approach you wrote makes sense, except I don't see why you would put the weight calculation in the `DatasetFolder` -- you shouldn't need to modify that class.
