### ISSUE TITLE
Out of memory during semseg eval

### ISSUE THREAD

**Issue by lewfish** [azavea/raster-vision#870]
A semseg eval job ran out of memory when running on Batch with 6000 MB allocated to it. I was surprised because the GeoTIFFs were around 9000x9000 each. (There were around 100 validation scenes.) I logged into the instance while it was running and noticed that the memory consumption gradually increased over the span of processing dozens of images until it crashed. It seems like there is some kind of memory leak, although this hasn't happened in the past when running Spacenet experiments which have hundreds or thousands of images.

**Comment by AdeelH** [comment]
Likely the same thing as #1115
