### ISSUE TITLE
Docker+GPU Install Question

### ISSUE THREAD

**Issue by joehoeller** [azavea/raster-vision#877]
How do you install RasterVision for CUDA and PyTorch together in docker w/ Tensorboard?

**Comment by lewfish** [comment]
`./docker/build --pytorch` should do it.

**Comment by joehoeller** [comment]
I’m making a custom dockerfile, do u have a link to a Dockerfile that pulls in all the deps for GPU and tensorboard I can look at?

**Comment by lewfish** [comment]
https://github.com/azavea/raster-vision/blob/master/Dockerfile-pytorch inherits from https://github.com/azavea/raster-vision/blob/master/Dockerfile

**Comment by lewfish** [comment]
See https://github.com/azavea/raster-vision/blob/master/docker/build#L33-L34

**Comment by joehoeller** [comment]
Got it, thanks!!

Can I use OpenCV v4.x and PyTorch v1.4 that is pre-compiled for CUDA?

Also wondering if I can replace NumPy w/ CuPy?

**Comment by lewfish** [comment]
I'm not sure if they will work, but it's worth a try.
