### ISSUE TITLE
Something up with a file named "aux"

### ISSUE THREAD

**Issue by Jonathan-Gore** [azavea/raster-vision#888]
Hey, when I try to clone the repo from github AND when I try to extract the compressed zip file I get similar errors about being unable to either clone or extract a file directory known as "aux"

For git I get this error:

fatal: cannot create directory at 'rastervision/command/aux': Invalid argument

and for 7zip I get this error {paraphrased since it's laid out in a nice graphical way}: the directory name is invalid: aux

Anyone have any ideas on what I'm doing wrong?

**Comment by jamesmcclain** [comment]
On Windows, the name `aux` refers to (what on Unix would be called) a device file.  Other such device files include `con` and `nul`.  Raster Vision is developed on Linux and Macintosh so this issue was not initially detected -- I think that it is being addressed.

**Comment by Jonathan-Gore** [comment]
Just pinging this issue, is there something particularly important that's stopping the "aux" file in the control folder from being renamed to "aux_" or something?
