### ISSUE TITLE
Improve interface and add docs for external commands

### ISSUE THREAD

**Issue by lewfish** [azavea/raster-vision#930]
If we maintain support for external commands (see https://github.com/azavea/raster-vision/pull/924) we should make the interface more polished. For example, instead of 

```
    setattr(to_my_little_friend, 'external', True)
    setattr(to_my_little_friend, 'job_queue', 'my-queue')
```

the `Pipeline` subclass can have fields such as 

```
external_commands = ['to_my_little_friend']
job_queues = {'to_my_little_friend': 'my_queue'}
```

Also, the concept of external commands needs to be discussed at several points in the Sphinx docs and probably PyDocs too. Even if people don't want to use external commands, they need to understand them if they want to modify the runner code.

**Comment by AdeelH** [comment]
#1047
