### ISSUE TITLE
Question on FCN, why use resize_bilinear instead of deconv

### ISSUE THREAD

**Issue by rw1993** [azavea/raster-vision#95]
In some other accomplishments , the 'c8 to r8' is done by deconv, but the FCN model here uses resize_bilinear?

**Comment by lewfish** [comment]
I had trouble getting deconvolution to work in Keras and I've also read that they cause some problems. See https://distill.pub/2016/deconv-checkerboard/. So an alternative way to upsample is to use resize_bilinear followed by a convolution.
