### ISSUE TITLE
output vector labels using labelstore works during evaluation but not when using bundle

### ISSUE THREAD

**Issue by TareqAlqutami** [azavea/raster-vision#953]
Hello,
for a semantic segmentation task, When I add a with_vector_output to the labelStore builder to output labels as polygons or buildings, It works for the evaluation scenes after training is completed. The outputs in the `predict` directory will contain predicted labels in both tif and geojson formats. But when I use the bundle to predict for new scenes, it only outputs labels in single-band raster format (.tif).
I tried both raster-vision versions 0.10 and 0.11 but both produce the same results.
Here is the labelStore code that is added to the scenes using .with_label_store:
```
python
vector_output = {'mode': 'polygons', 'class_id': 1, 'denoise': 3}
label_store = rv.LabelStoreConfig.builder(rv.SEMANTIC_SEGMENTATION_RASTER) \
                                             .with_vector_output([vector_output]).build()
```

Here is the scene,groundTruthLabelSource and predictionLabelStore sections of the bundle_config.json:

`
"scene": { "id": "train_austin1", "rasterSource": { "sourceType": "RASTERIO_SOURCE", "channelOrder": [ 0, 1, 2 ], "rasterioSource": { "uris": [ "BUNDLE" ], "xShiftMeters": 0.0, "yShiftMeters": 0.0 } }, "groundTruthLabelSource": { "sourceType": "SEMANTIC_SEGMENTATION_RASTER", "semanticSegmentationLabelSource": { "source": { "sourceType": "RASTERIZED_SOURCE", "rasterizedSource": { "vectorSource": { "geojson": { "uri": "/opt/src/code/inria/train/small_test_vector/austin1.geojson" }, "sourceType": "GEOJSON_SOURCE", "classIdToFilter": { "1": [ "==", "DN", 255.0 ] } }, "rasterizerOptions": { "backgroundClassId": 2, "allTouched": false } } } } }, "predictionLabelStore": { "storeType": "SEMANTIC_SEGMENTATION_RASTER", "semanticSegmentationRasterStore": { "rgb": false, "vectorOutput": [ { "denoise": 2, "uri": "", "mode": "polygons", "classId": 1, "buildingOptions": { "minAspectRatio": 1.6180000305175781, "elementWidthFactor": 0.5, "elementThickness": 0.0010000000474974513 } } ] } }
`

How to ensure the output labels are vectors?

**Comment by lewfish** [comment]
Yes, the `predict` command does not handle the vector output. The reason is that it wouldn't know where to put the (potentially many) vector prediction files since there is only a single CLI argument for the output. A potential fix is to interpret the output CLI argument as the path to a directory, and then put all the files there. This would take some work (probably not huge, but not trivial either), and it's low-priority for us right now. If you were interested in making a PR, I could try to give you some guidance.

**Comment by lewfish** [comment]
This was implemented in https://github.com/azavea/raster-vision/pull/980
