### ISSUE TITLE
pytorch_learner examples need to be updated

### ISSUE THREAD

**Issue by AdeelH** [azavea/raster-vision#965]
[pytorch_learner/learner_pipeline.py#L16](https://github.com/azavea/raster-vision/blob/master/rastervision_pytorch_learner/rastervision/pytorch_learner/learner_pipeline.py#L16) calls `ClassificationLearnerConfig.build()`
```
learner = learner_cfg.build(learner_cfg, self.tmp_dir)
```
which has the signature
```
def build(self, tmp_dir, model_path=None):
    ...
```
So the above call should, in effect, map `learner_cfg` to `tmp_dir` and `tmp_dir` to `model_path`.

I get an error consistent with this when I run a chip classification experiment (raster-vision/rastervision_pytorch_learner/rastervision/pytorch_learner/examples/classification.py). But I don't get the same error on running a semantic segmentation experiment, which is a little confusing.

**Comment by lewfish** [comment]
As we discussed, this only occurs in the `pytorch_learner` examples (which are not the `pytorch_backend` examples discussed in the docs at https://docs.rastervision.io/en/latest/examples.html) which work against an older version of RV and need to be updated. So, I'm editing the name of this issue to reflect that.

**Comment by AdeelH** [comment]
@lewfish, how do you feel about removing [these examples](https://github.com/azavea/raster-vision/tree/master/rastervision_pytorch_learner/rastervision/pytorch_learner/examples) entirely?

**Comment by lewfish** [comment]
> @lewfish, how do you feel about removing [these examples](https://github.com/azavea/raster-vision/tree/master/rastervision_pytorch_learner/rastervision/pytorch_learner/examples) entirely?

Sure, it seems pretty obsolete and not being used.
