### ISSUE TITLE
Track pystac versions

### ISSUE THREAD

**Issue by moradology** [azavea/raster-vision#968]
Pystac generated catalogs are completely incompatible between minor versions at the moment and development efforts (aimed at 0.4) have required us to write `Dockerfile`s to extend the RV images (which use 0.3). This will be simpler once things stabilize a bit more in pystac but it might be sensible to explicitly track pystac versions in the `requirements.txt` for this project's `Dockerfile`

**Comment by AdeelH** [comment]
Pystac is being tracked in https://github.com/azavea/raster-vision/blob/master/rastervision_core/requirements.txt so closing this.
