### ISSUE TITLE
Add MultiRasterSource

### ISSUE THREAD

**Issue by lewfish** [azavea/raster-vision#973]
We would like to be able to use different bands from multiple GeoTIFFs for each scene. To do this, we can add a `MultiRasterSource` which combines several raster sources into a single one. For example, the following would create a raster source where bands 0 and 2 come from file1.tif and band 1 comes from file2.tif.

```
MultiRasterSourceConfig(
   raster_sources=[
       (RasterioSource('file1.tif'), (0, 2)),
       (RasterioSource('file2.tif'), (1,)])
```

**Comment by lewfish** [comment]
@jamesmcclain @AdeelH This is the feature that @echeipesh had requested.

**Comment by lewfish** [comment]
This should be completed by the end of next sprint, but sooner is better.

**Comment by AdeelH** [comment]
It is not obvious to me how to combine the crs_transformers of the sub raster sources. RV seems to use that to output predicted labels as geojsons. So for now, I have disabled that functionality in the multi raster source example (which is separate from the normal SS example) by removing the `vector_output` option from `SemanticSegmentationLabelStoreConfig`. It only outputs predictions as tifs now.
