### ISSUE TITLE
Export models in standardized "archival" format

### ISSUE THREAD

**Issue by lewfish** [azavea/raster-vision#974]
RV model bundles contain RV configuration which is used to recreate the model architecture at runtime. This works if we are using the model within RV, but makes it harder to use in other settings. We would like to also export the model in a more "archival" format so it can be instantiated outside of RV. @AdeelH researched this and found that TorchHub might be a good candidate for a way to do this https://pytorch.org/docs/stable/hub.html

Before starting work on this, we should have a discussion to see if this is the best approach and how we would add support for it in RV.

**Comment by AdeelH** [comment]
We should use [ONNX](https://onnx.ai/get-started.html) for this.
