### ISSUE TITLE
Add Support for External Architectures

### ISSUE THREAD

**Issue by jamesmcclain** [azavea/raster-vision#975]
Adding easy support for externally-defined architectures seems as though it might be an interesting feature to have.  In particular, I am interested in being able to

1. point raster vision to some architecture definition code (in some understood, canonical format) and train a model that uses that architecture (see #927 for a proto-example), and
2. generate a model bundle that contains the architecture definition code (or possibly a reference to it) within itself in addition to the model weights (relates to #974, though that issue seems to contemplate doing this for existing raster vision architectures [which I am also in favor of])

@AdeelH discovered [torch hub](https://pytorch.org/docs/stable/hub.html) which looks as if it provides a clean way to accomplish the loading and referencing of externally-defined architectures.  Some questions that came up while reading through the documentation: is it possible to reference a particular commit on GitHub? (Branches and tags are both mentioned, but untagged commits are not [even if this is not supported it is not a deal-breaker for me].)  Also, there may be instances when it is convenient to save the actual architecture code in the bundle rather than a reference to it: that does not seem to be supported.

Tagging @AdeelH @lewfish

**Comment by AdeelH** [comment]
>Also, there may be instances when it is convenient to save the actual architecture code in the bundle rather than a reference to it: that does not seem to be supported.

Since, `torch.hub.load()` first downloads the repo and then does its thing, it should be possible to adapt its code to make it work directly from a local dir.

**Comment by jamesmcclain** [comment]
This looks promising: https://pytorch.org/docs/master/generated/torch.jit.save.html
