### ISSUE TITLE
Provide grouping mechanism for evaluation

### ISSUE THREAD

**Issue by lewfish** [azavea/raster-vision#984]
Currently the validation scenes are each evaluated individually and then averaged together. We would like to be able to specify groups of scenes, and compute average metrics over each group. For example, this would allow us to compute the score for rural vs. urban scenes. Using the below config, you would get an `eval.json` with entries for urban and rural in addition to averaged over all scenes.

```python
DatasetConfig(
   train_scenes=..., validation_scenes=[SceneConfig(id='nyc'), SceneConfig(id='farmland')],test_scenes=[], 
   scene_groups={
      'urban': ['ny',],
      'rural: ['farmland']
   })
```

In addition, two scene groups should be added automatically: `validation` and `test` based on the scene ids within `validation_scenes`, and `test_scenes`. This way, we can compute separate metrics for the validation and test set. Note that currently the test set is not used by the eval command at all, and is only used by predict.

**Comment by AdeelH** [comment]
Are all scenes usually of the same size? If not, the current scheme of averaging the average metrics over each scene might also be causing some Simpson's effects: https://en.wikipedia.org/wiki/Simpson%27s_paradox

**Comment by lewfish** [comment]
No, we're computing a weighted average over the scores for scenes, where the weight is the `gt_count` which is the number of ground truth labels for the scene.

**Comment by AdeelH** [comment]
Ah, okay. That should not be a problem then.
