### ISSUE TITLE
Support arbitrary Albumentations augmentations

### ISSUE THREAD

**Issue by AdeelH** [azavea/raster-vision#995]
Currently, RV only supports a limited number of augmentations (listed below) and does not support setting their parameters.
```python3
augmentors = [
    'Blur', 'RandomRotate90', 'HorizontalFlip', 'VerticalFlip', 'GaussianBlur',
    'GaussNoise', 'RGBShift', 'ToGray'
]
```
It should be possible to support arbitrary augmentations without any serialization problems if we make use of Albumentation's [serialization utilities](https://github.com/albumentations-team/albumentations_examples/blob/master/notebooks/serialization.ipynb), namely `A.to_dict()` and `A.from_dict()`.  For example:
```python3
augmentation = A.Compose([
	A.RandomCrop(768, 768),
	A.OneOf([
		A.RGBShift(),
		A.HueSaturationValue()
	])
])

ChipClassificationConfig(
	...,
	augmentation=A.to_dict(augmentation)
)
```

**Comment by lewfish** [comment]
Sounds good
