### ISSUE TITLE
Scripts in `integration_tests/util/` need to be updated

### ISSUE THREAD

**Issue by jamesmcclain** [azavea/raster-vision#997]
The integration test `integration_tests/util/generate_scene.py` uses `ClassMap` and `ClassItem` which seem to no longer exist.

**Comment by lewfish** [comment]
That's script was just used to generate some data that is used in the integration test, but isn't actually run as part of the test itself. But you're right that it's out of date.

**Comment by jamesmcclain** [comment]
:rofl:
