### ISSUE TITLE
DataConfig.img_sz should be independent of RVPipelineConfig.train_chip_sz

### ISSUE THREAD

**Issue by AdeelH** [azavea/raster-vision#998]
`DataConfig.img_sz` is the size that the images are resized to before being consumed by the model.

`RVPipelineConfig.train_chip_sz` is the chip size.

Currently, the `PyTorchLearnerBackendConfig`'s set `DataConfig.img_sz` = `RVPipelineConfig.train_chip_sz`, 
https://github.com/azavea/raster-vision/blob/2a4b834f7ac4378e8111740b931a677287208e7a/rastervision_pytorch_backend/rastervision/pytorch_backend/pytorch_chip_classification_config.py#L21
which seems unnecessarily restrictive. At least in the case of classification, where the model output is not related to image size, there should be no issues with chip size and model output size compatibility.

**Implementation**
This can be done simply by making the `img_sz` option available in `PyTorchLearnerBackendConfig` and then passing it on to `DataConfig.img_sz`.

**Comment by lewfish** [comment]
> Currently, the `PyTorchLearnerBackendConfig`'s set `DataConfig.img_sz` = `RVPipelineConfig.train_chip_sz`,
> https://github.com/azavea/raster-vision/blob/2a4b834f7ac4378e8111740b931a677287208e7a/rastervision_pytorch_backend/rastervision/pytorch_backend/pytorch_chip_classification_config.py#L21
> 
> 
> which seems unnecessarily restrictive. At least in the case of classification, where the model output is not related to image size, there should be no issues with chip size and model output size compatibility.
> **Implementation**
> This can be done simply by making the `img_sz` option available in `PyTorchLearnerBackendConfig` and then passing it on to `DataConfig.img_sz`.

I agree that it should be easy to add for classification and regression. What is the use case / motivation for this?

**Comment by AdeelH** [comment]
I originally thought about this in the context of reducing inference time of scenes by increasing the size of chips (= fewer chips), but without increasing the model's compute/memory cost (i.e. model input size remains the same).

But a simpler answer is that this functionality is already built in, but implicitly disabled. The `Learner` already uses a resize transform; it's just that it currently doesn't have any effect.
https://github.com/azavea/raster-vision/blob/2a4b834f7ac4378e8111740b931a677287208e7a/rastervision_pytorch_learner/rastervision/pytorch_learner/learner.py#L331-L333

This would just allow the user access to this functionality.

**Comment by lewfish** [comment]
Sounds good.
