### ISSUE TITLE
Filter out images that are >x% NODATA

### ISSUE THREAD

**Issue by AdeelH** [azavea/raster-vision#999]
Currently, RV does not filter out chips that are mostly NODATA and therefore not useful for training/validation. Example chip:

![2fdf89e12a049f33ac20cafdf561c930c93ca211d072e7121846cf7f8cde20d4-1852](https://user-images.githubusercontent.com/13014700/93469249-acf54b00-f909-11ea-9a43-fc780f851753.png)

Would be useful to have an option to filter these chips out of the dataset.

**Comment by lewfish** [comment]
Sounds good. There is already some similar logic, but it doesn't work for all pipelines, and doesn't use a threshold.

For chip classification see: https://github.com/azavea/raster-vision/blob/master/rastervision_core/rastervision/core/rv_pipeline/chip_classification.py#L20-L21

For object detection see: https://github.com/azavea/raster-vision/blob/master/rastervision_core/rastervision/core/rv_pipeline/object_detection.py#L80-L82
